name: SfsPipeline
channels:
  - conda-forge
dependencies:
  - python>=3.12
  - ipython
  - ipykernel
  - duckdb
  - duckdb-cli
  - python-duckdb 
  - fire
  - gdal
  - geopandas
  - fiona
  - libgdal-arrow-parquet
  - lark
  - matplotlib-base
  - numpy
  - pvl
  - polars
  - pystac
  - pip
  - pyarrow
  - pyproj
  - rclone
  - rasterio
  - sh
  - jq
  - fzf
  - shapely
  - pip:
    - --editable .
    - moody
