[build-system]
requires = ["setuptools>=62.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "loony"
description = "Ames Stereo Pipeline SfS tools"
requires-python = ">=3.12"
dynamic = ["version", "readme"]
classifiers = [
    "Private :: Do Not Upload",
    "Development Status :: 3 - Alpha",
    "Programming Language :: Python :: 3.12",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Astronomy",
    "Topic :: Scientific/Engineering :: GIS",
    "Topic :: Scientific/Engineering :: Visualization",
]
authors = [
    {name = "Dr. Andrew Annex", email="andrew.m.annex@nasa.gov"}
]
keywords = ["SfS", "Tools"]
dependencies = [
    "sh",
    "rasterio",
    "duckdb",
    "pyproj",
    "geopandas",
    "polars",
    "fire",
    "shapely",
    "numpy"
]

[project.urls]
Repository = "https://github.com/NeoGeographyToolkit/sfstools.git"

[tool.setuptools.dynamic]
version = {attr = "loony.__version__"}
readme = {file = "README.md"}

[tool.setuptools.packages.find]
where = ["src"]
include = ["resources/"]
namespaces = false

[project.scripts]
get-current-provenance = "loony.get_current_provenance:main"
sfs-cover = "loony.new_sfs_cover:main"
preprocess-cumulative-index = "loony.process_lroc_cumulative_index:main"
process-cumulative-index = "loony.resources.process:main"