[build-system]
requires = ["setuptools>=62.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "sfs"
description = "Ames Stereo Pipeline SfS tools"
requires-python = ">=3.12"
dynamic = ["version", "readme"]
classifiers = [
    "Private :: Do Not Upload",
    "Development Status :: 3 - Alpha",
    "Programming Language :: Python :: 3.12",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Astronomy",
    "Topic :: Scientific/Engineering :: GIS",
    "Topic :: Scientific/Engineering :: Visualization",
]
authors = [
    {name = "Dr. Andrew Annex", email="andrew.m.annex@nasa.gov"}
]
keywords = ["SfS", "Tools"]
dependencies = [
    "sh",
    "rasterio",
    "duckdb",
    "fiona",
    "pyproj",
    "geopandas",
    "polars",
    "fire",
    "shapely",
    "numpy",
    "pyarrow"
]

[project.urls]
Repository = "https://github.com/NeoGeographyToolkit/SfsPipeline.git"

[tool.setuptools.packages.find]
where = ["."]
namespaces = false

[tool.setuptools.dynamic]
version = {attr = "sfs.__version__"}
readme = {file = "README.md"}

[tool.setuptools.package-data]
"*" = ["*.xml"]


[project.scripts]
provenance           = "sfs.get_current_provenance:main"
prep-index           = "sfs.process_lroc_cumulative_index:main"
make-index           = "sfs.resources.process:main"
find-image-overlaps  = "sfs.find_overlaps_for_bundle_adjust:main"
sfs-cover            = "sfs.new_sfs_cover:main"
find-stereo          = "sfs.find_stereo_pairs:main"
wkt-to-ullr          = "sfs.wkt_to_ullr:main"
wkt-to-projwin       = "sfs.wkt_to_projwin:main"
wkt-round-out        = "sfs.wkt_round_out:main"
setops               = "sfs.setops:main"
tri-plot             = "sfs.triangulation_plot:main"
verify-ba            = "sfs.verify_bundle_adjust:main"
stereo-from-ba       = "sfs.get_stereo_pairs_from_bundle_adjust:main"
solar-az-plot        = "sfs.solar_az_animate:main"
lit-select           = "sfs.lit_select:main"
update-db            = "sfs.update_db_from_footprints:main"
filter-db            = "sfs.filter_db_by_verify_ba:main"