#!/bin/bash
#PBS -N pbs_ba_pt1
#PBS -j oe                      
#PBS -k oe                      
#PBS -l select=10:ncpus=20:model=ivy,walltime=50:00:00        
#PBS -q normal                  
#PBS -m abe                     
#PBS -M andrew.m.annex@nasa.gov 
#PBS -o pbs_ba_pt1.log   
#PBS -r y                       
#PBS -S /bin/bash               
#PBS -V                         
#PBS -W group_list=e2305     

# Enable stepwise debugging if DEBUG is set to "true"
if [[ "$DEBUG" == "true" ]]; then
    trap '(read -p "[$BASH_SOURCE:$LINENO] $BASH_COMMAND ")' DEBUG
fi

# define usage once
USAGE="qsub -v DEM=/path/to/dem.tif,IMAGES=/path/to/list/of/tifs.txt,CAMERAS=/path/to/list/of/jsons.txt,OUT=ba0/run $0"
# Ensure a DEM was provided
if [ -z "$DEM" ]; then
    echo "Error: DEM is not set. Use $USAGE"
    exit 1
fi
echo "DEM file: $DEM"
# Ensure a cub image list is provided
if [ -z "$IMAGES" ]; then
    echo "Error: IMAGES is not set. Use $USAGE"
    exit 1
fi
echo "Path to images list: $IMAGES"
# Ensure a camera list is provided
if [ -z "$CAMERAS" ]; then
    echo "Error: CAMERAS is not set. Use $USAGE"
    exit 1
fi
echo "Path to cameras list: $CAMERAS"
# Ensure the map projected images + the DEM as the last file are included as a list
if [ -z "$MAPPROJ_DATA" ]; then
    echo "Error: IMAGES is not set. Use $USAGE"
    exit 1
fi
echo "Path to mapprojected data list: $MAPPROJ_DATA"
# Ensure a output prefix is provided
if [ -z "$OUT" ]; then
    echo "Error: OUT is not set. Use $USAGE"
    exit 1
fi
echo "Output Prefix: $OUT"
##############################################
# Change to the working directory
echo Working directory is $PBS_O_WORKDIR
cd $PBS_O_WORKDIR
echo "machine is $(uname -a)"
echo "machine file is $PBS_NODEFILE"
# get the number of unique nodes 
if [[ -z "$PBS_NODEFILE" || ! -f "$PBS_NODEFILE" ]]; then
    NUM_NODES=1
else
    NUM_NODES=$(sort -u "$PBS_NODEFILE" | wc -l)
fi
echo "running on $NUM_NODES nodes"
echo
##############################################
# source asap environment
source init_asap.sh
# echo out ISISDATA and ISISROOT
echo ISIS data is $ISISDATA 
echo ISIS root is $ISISROOT
# echo out PATH
echo PATH is $PATH

# https://stereopipeline.readthedocs.io/en/latest/tools/parallel_bundle_adjust.html
# --stop-point 2 should stop before optimization which only works on 1 node

parallel_bundle_adjust       \
  --stop-point 2             \
  --nodes-list ${PBS_NODEFILE} \
  --image-list ${IMAGES}    \
  --camera-list ${CAMERAS}  \
  --mapproj-dem ${DEM}      \
  --mapprojected-data ${MAPPROJ_DATA} \
  --nodata-value 0.001      \
  --ip-per-tile  400        \
  --ip-per-image 20000      \
  --overlap-limit 50        \
  --match-first-to-last     \
  --num-iterations 50       \
  --matches-per-tile 100    \
  --num-passes 2            \
  --min-matches 10          \
  --max-pairwise-matches 1000 \
  --camera-weight 0           \
  --save-intermediate-cameras \
  --robust-threshold 0.5      \
  --tri-weight 0.1            \
  --tri-robust-threshold 0.25 \
  --min-triangulation-angle 0.1 \
  --remove-outliers-params "75.0 3.0 100 100"    \
  -o ${OUT} 

if [[ -z "$DEBUG" ]]; then 
  # now start part 2, using same input parameters as part 1
  qsub -W depend=afterok:${PBS_JOBID} -v DEM=$DEM,IMAGES=$IMAGES,CAMERAS=$CAMERAS,OUT=$OUT bundle_adjust_pt2.pbs
  # we are now done!
  echo "Part 2 job submitted at $(date)"
fi
# we are now done!
echo "Job finished at $(date)"
