#!/bin/bash
#PBS -N pbs_ba_pt0
#PBS -j oe                      
#PBS -k oe                      
#PBS -l select=32:ncpus=20:model=ivy,walltime=08:00:00        
#PBS -q normal                
#PBS -m abe                     
#PBS -M andrew.m.annex@nasa.gov 
#PBS -o pbs_ba_pt0.log   
#PBS -r y                       
#PBS -S /bin/bash               
#PBS -V                         
#PBS -W group_list=e2305     

# Enable stepwise debugging if DEBUG is set to "true"
if [[ "$DEBUG" == "true" ]]; then
    trap '(read -p "[$BASH_SOURCE:$LINENO] $BASH_COMMAND ")' DEBUG
fi

# define usage once
USAGE="qsub -v DEM=/path/to/dem.tif,IMAGES=/path/to/list/of/tifs.txt,CAMERAS=/path/to/list/of/jsons.txt,MAPPROJ_DATA=/path/to/mapproj_data.txt,OVERLAP_LIST=/path/to/overlap_list.txt,BA_PREFIX=ba0/run $0"
# Ensure a DEM was provided
if [ -z "$DEM" ]; then
    echo "Error: DEM is not set. Use $USAGE"
    exit 1
fi
echo "DEM file: $DEM"
# Ensure a cub image list is provided
if [[ -z "$IMAGES" ]]; then
    echo "Error: IMAGES is not set. Use $USAGE"
    exit 1
fi
echo "Path to images list: $IMAGES"
# Ensure a camera list is provided
if [[ -z "$CAMERAS" ]]; then
    echo "Error: CAMERAS is not set. Use $USAGE"
    exit 1
fi
echo "Path to cameras list: $CAMERAS"
# Ensure the map projected images + the DEM as the last file are included as a list
if [[ -z "$MAPPROJ_DATA" ]]; then
    echo "Error: MAPPROJ_DATA is not set. Use $USAGE"
    exit 1
fi
echo "Path to mapprojected data list: $MAPPROJ_DATA"
# get overlap list file
if [[ -z "$OVERLAP_LIST" ]]; then
    echo "Error: OVERLAP_LIST is not set. Use $USAGE"
    exit 1
fi
echo "Path to overlap list: $OVERLAP_LIST"
# Ensure a output prefix is provided
if [[ -z "$BA_PREFIX" ]]; then
    echo "Error: BA_PREFIX is not set. Use $USAGE"
    exit 1
fi
echo "Output Prefix: $BA_PREFIX"
# Ensure the work dir is set to something
if [[ -z "$WORKDIR" ]]; then
    # we will default to the current working directory wherever that is
    export WORKDIR="$PWD"
fi
echo "Workdir: $WORKDIR"
##############################################
# Check if the user want's this acutally submitted to PBS
if [[ -n $SUBMIT ]]; then
    # Tell user you requested to submit and then wait 15 seconds to allow user to exit just in case!
    echo "User requested to submit to PBS!!!!! You have 15 seconds to abort!!!"
    # unset SUBMIT so that this isn't recursive
    unset SUBMIT
    # unset DEBUG so that we don't debug inside the job
    unset DEBUG
    # echo SUBMIT and DEBUG as sanity check
    echo "DEBUG is $DEBUG and SUBMIT is $SUBMIT" 
    # actually sleep
    sleep 15
    # submit to qsub
    submit_name="pbs_ba_pt0_${BA_PREFIX%/*}"
    exec qsub -N "$submit_name" -o "$WORKDIR/$submit_name.log" -V "$0"
    # be sure to exit the script at this point
    exit 0
fi
##############################################
# IF we are actually on PBS do another unset on DEBUG 
# just in case to avoid long waits for quick exits
if [[ -n $PBS_JOBID ]]; then
    # log
    echo "Checking current DEBUG variable value: $DEBUG"
    # unset it
    unset DEBUG
    # log
    echo "If DEBUG was not unset it should now be not set: $DEBUG"
fi
# Change to the working directory
echo Working directory is "$PBS_O_WORKDIR"
if [[ -n $PBS_O_WORKDIR ]]; then
    cd "$PBS_O_WORKDIR" || exit
fi
echo "machine is $(uname -a)"
echo "machine file is $PBS_NODEFILE"
# get the number of unique nodes 
if [[ -z "$PBS_NODEFILE" || ! -f "$PBS_NODEFILE" ]]; then
    NUM_NODES=1
else
    echo "machines are: $(cat $PBS_NODEFILE | sort -u)"
    NUM_NODES=$(sort -u "$PBS_NODEFILE" | wc -l)
fi
echo "running on $NUM_NODES nodes"
echo
##############################################
# source asp environment
source init_asp.sh
# echo out ISISDATA and ISISROOT
echo ISIS data is "$ISISDATA" 
echo ISIS root is "$ISISROOT"
# echo out PATH
echo PATH is "$PATH"
##############################################

# https://stereopipeline.readthedocs.io/en/latest/tools/parallel_bundle_adjust.html
# --stop-point 2 should stop before optimization which only works on 1 node
# bug in parallel_bundle_adjust prevents allocating more than the number of nodes jobs to run simultaenously 
# eg, you have 16 nodes, want to run 4 per, you can only ever run 1 per (max 16), but then --processes can lower that
# so you can almost never run more than 1 job per node, solution allocate many nodes but with 1 process or fix via pr
# construct args

## internally parallel_bundle_adjust uses --max-jobs parameter for processes
## if you have 16 nodes with 40 cores each (20 physical) and want 16*20 jobs running in parallel, you need to set --max-jobs to 320
## then you would set --process to 320 and --threads to 2
## if you want 4 threads per job, for 1 node you can have 5 jobs (4*5=20), and then 5 jobs * 16 nodes is 80 concurrent jobs
## if 4 per node but want some buffer, then 4*16 = 64
## I think I want 3 jobs per node, with 5 threads per job, so ask for more nodes, assume only 60 gb of ram 
## per node, so request more cpus than you need to expand memory capacity (todo ask hec if I can request fewer cores but get the same ram)
## with 3 jobs per node, approx 20 gb per job should be available. 

args=(
      --entry-point 0
      --stop-point 1          
      --nodes-list "$PBS_NODEFILE"    
      --image-list "$IMAGES" 
      --camera-list "$CAMERAS"
      --mapproj-dem "$DEM"      
      --mapprojected-data-list "$MAPPROJ_DATA" 
      --overlap-list "$OVERLAP_LIST"
      --processes 5            
      --threads 4               
      --nodata-value 0.001      
      --ip-detect-method 1      
      --ip-per-tile  400        
      --ip-per-image 20000      
      --num-iterations 500      
      --num-passes 2            
      --min-matches 10          
      --max-pairwise-matches 2000 
      --camera-weight 0           
      --save-intermediate-cameras 
      --robust-threshold 2.0      
      --tri-weight 0.1            
      --tri-robust-threshold 0.25 
      --min-triangulation-angle 0.1 
      --remove-outliers-params "75.0 3.0 100 100"
      -o "$BA_PREFIX"
)
# create output folders as needed TODO: guard with check on debug?
LOGS_FOLDER="$WORKDIR/logs"
JOBS_FOLDER="$WORKDIR/jobs"
mkdir -p "$LOGS_FOLDER"
mkdir -p "$JOBS_FOLDER"
# set log file names
LOG_FILE="$LOGS_FOLDER/pbs_ba_pt0_${BA_PREFIX%/*}_$(date +"%Y-%m-%d_%H-%M-%S")_log.txt"
JOB_FILE="$JOBS_FOLDER/pbs_ba_pt0_${BA_PREFIX%/*}_job.log"
# for annoying reasons I can't seem to pass this in the array
parallel_opts="--resume-failed --sshdelay 0.1 --memfree 22G --joblog $JOB_FILE"
# start call
if [[ -z "$DEBUG" && -n $PBS_JOBID ]]; then 
    echo "Environment Variables: "
    env
    echo "Args: "
    echo "${args[@]}"
    echo "Parallel options: "
    echo "$parallel_opts"
    echo "Log File: "
    echo "$LOG_FILE"
    echo "Job File: "
    echo "$JOB_FILE"
    echo "Parallel has started at $(date)"
    parallel_bundle_adjust "${args[@]}" --parallel-options "$parallel_opts" | grep -E -v "Writing|Saving|stats:" &> "$LOG_FILE"
    # The jobs have actually completed 
    echo "Parallel has finished with all jobs at $(date)"
    # move the joblog file to preserve its state and to avoid re-running it
    mv "$JOB_FILE" "$JOBS_FOLDER/completed_${JOB_FILE##*/}"
else
    # I am debugging of a pfe or something
    echo "would have run: "
    echo "parallel_bundle_adjust" "${args[@]}"
fi
# we are now done!
echo "Job finished at $(date)"
