#!/bin/bash
#PBS -N pbs_ba_pt1
#PBS -j oe                      
#PBS -k oe                      
#PBS -l select=6:ncpus=20:model=ivy,walltime=04:00:00        
#PBS -q normal                 
#PBS -m abe                     
#PBS -M andrew.m.annex@nasa.gov 
#PBS -o pbs_ba_pt1.log   
#PBS -r y                       
#PBS -S /bin/bash               
#PBS -V                         
#PBS -W group_list=e2305     
# twelve nodes for 286 images and 1600 pairs took about 45 minutes wall time
# Enable stepwise debugging if DEBUG is set to "true"
if [[ "$DEBUG" == "true" ]]; then
    trap '(read -p "[$BASH_SOURCE:$LINENO] $BASH_COMMAND ")' DEBUG
fi

# define usage once
USAGE="qsub -v DEM=/path/to/dem.tif,IMAGES=/path/to/list/of/tifs.txt,CAMERAS=/path/to/list/of/jsons.txt,MAPPROJ_DATA=/path/to/mapproj_data.txt,OVERLAP_LIST=/path/to/overlap_list.txt,BA_PREFIX=ba0/run $0"
# Ensure a DEM was provided
if [ -z "$DEM" ]; then
    echo "Error: DEM is not set. Use $USAGE"
    exit 1
fi
echo "DEM file: $DEM"
# Ensure a cub image list is provided
if [ -z "$IMAGES" ]; then
    echo "Error: IMAGES is not set. Use $USAGE"
    exit 1
fi
echo "Path to images list: $IMAGES"
# Ensure a camera list is provided
if [ -z "$CAMERAS" ]; then
    echo "Error: CAMERAS is not set. Use $USAGE"
    exit 1
fi
echo "Path to cameras list: $CAMERAS"
# Ensure the map projected images + the DEM as the last file are included as a list
if [ -z "$MAPPROJ_DATA" ]; then
    echo "Error: MAPPROJ_DATA is not set. Use $USAGE"
    exit 1
fi
echo "Path to mapprojected data list: $MAPPROJ_DATA"
# get overlap list file
if [ -z "$OVERLAP_LIST" ]; then
    echo "Error: OVERLAP_LIST is not set. Use $USAGE"
    exit 1
fi
echo "Path to overlap list: $OVERLAP_LIST"
# Ensure a output prefix is provided
if [ -z "$BA_PREFIX" ]; then
    echo "Error: BA_PREFIX is not set. Use $USAGE"
    exit 1
fi
echo "Output Prefix: $BA_PREFIX"
##############################################
# Check if the user want's this acutally submitted to PBS
if [[ -n $SUBMIT ]]; then
    # Tell user you requested to submit and then wait 15 seconds to allow user to exit just in case!
    echo "User requested to submit to PBS!!!!! You have 15 seconds to abort!!!"
    # unset SUBMIT so that this isn't recursive
    unset SUBMIT
    # unset DEBUG so that we don't debug inside the job
    unset DEBUG
    # echo SUBMIT and DEBUG as sanity check
    echo "DEBUG is $DEBUG and SUBMIT is $SUBMIT" 
    # actually sleep
    sleep 15
    # submit to qsub
    exec qsub -v DEM="$DEM",IMAGES="$IMAGES",CAMERAS="$CAMERAS",MAPPROJ_DATA="$MAPPROJ_DATA",OVERLAP_LIST="$OVERLAP_LIST",BA_PREFIX="$BA_PREFIX" "$0"
    # be sure to exit the script at this point
    exit 0
fi
##############################################
# IF we are actually on PBS do another unset on DEBUG 
# just in case to avoid long waits for quick exits
if [[ -n $PBS_JOBID ]]; then
    # log
    echo "Checking current DEBUG variable value: $DEBUG"
    # unset it
    unset DEBUG
    # log
    echo "If DEBUG was not unset it should now be not set: $DEBUG"
fi
# Change to the working directory
echo Working directory is $PBS_O_WORKDIR
cd $PBS_O_WORKDIR
echo "machine is $(uname -a)"
echo "machine file is $PBS_NODEFILE"
# get the number of unique nodes 
if [[ -z "$PBS_NODEFILE" || ! -f "$PBS_NODEFILE" ]]; then
    NUM_NODES=1
else
    echo "machines are: $(cat $PBS_NODEFILE | sort -u)"
    NUM_NODES=$(sort -u "$PBS_NODEFILE" | wc -l)
fi
echo "running on $NUM_NODES nodes"
echo
##############################################
# source asap environment
source init_asap.sh
# echo out ISISDATA and ISISROOT
echo ISIS data is $ISISDATA 
echo ISIS root is $ISISROOT
# echo out PATH
echo PATH is $PATH

# https://stereopipeline.readthedocs.io/en/latest/tools/parallel_bundle_adjust.html
# --stop-point 2 should stop before optimization which only works on 1 node

# construct args
args=(
      --stop-point 2          
      --nodes-list "$PBS_NODEFILE"    
      --image-list "$IMAGES" 
      --camera-list "$CAMERAS"
      --mapproj-dem "$DEM"      
      --mapprojected-data-list "$MAPPROJ_DATA" 
      --overlap-list "$OVERLAP_LIST"
      --processes 4             
      --threads 4               
      --nodata-value 0.001      
      --ip-detect-method 1      
      --ip-per-tile  400        
      --ip-per-image 20000      
      --num-iterations 500      
      --num-passes 2            
      --min-matches 10          
      --max-pairwise-matches 2000 
      --camera-weight 0           
      --save-intermediate-cameras 
      --robust-threshold 2.0      
      --tri-weight 0.1            
      --tri-robust-threshold 0.25 
      --min-triangulation-angle 0.1 
      --verbose 
      --remove-outliers-params "75.0 3.0 100 100"
      -o "$BA_PREFIX"
)
# for annoying reasons I can't seem to pass this in the array
parallel_opts="--resume-failed --sshdelay 0.5 --memfree 30G --joblog $HOME/pbs_ba_pt1_${BA_PREFIX:0:3}_job.log"
# start call
if [[ -z "$DEBUG" && -n $PBS_JOBID ]]; then 
    parallel_bundle_adjust "${args[@]}" --parallel-options "$parallel_opts" | grep -E -v "Writing|Saving"
    # The jobs have actually completed 
    echo "Parallel has finished with all jobs at $(date)"
    # move the joblog file to preserve its state and to avoid re-running it
    mv "$HOME/pbs_ba_pt1_${BA_PREFIX:0:3}_job.log" "$HOME/completed_$(date +"%Y-%m-%d_%H-%M-%S")_pbs_ba_pt1_${BA_PREFIX:0:3}_job.log"
else
    # I am debugging of a pfe or something
    echo "would have run: "
    echo "parallel_bundle_adjust ${args[@]}"
fi
# we are now done!
echo "Job finished at $(date)"
