#!/bin/bash
#PBS -N pbs_ba_pt2
#PBS -j oe                      
#PBS -k oe                      
#PBS -l select=1:ncpus=36:mem=500GB,walltime=24:00:00      
#PBS -q ldan
#PBS -m abe                     
#PBS -o pbs_ba_pt2.log   
#PBS -r y                       
#PBS -S /bin/bash               
#PBS -V                         
#PBS -W group_list=e2305     
# TODO run this on the AMD nodes?
# TODO LDAN bigmem nodes https://www.nas.nasa.gov/hecc/support/kb/how-to-get-more-memory-for-your-pbs-job_222.html
# LDAN detail https://www.nas.nasa.gov/hecc/support/kb/lou-data-analysis-nodes_413.html
# TODO use $TMPDIR and mv to lfs after finishing https://www.nas.nasa.gov/hecc/support/kb/memory-usage-overview_216.html
# Enable stepwise debugging if DEBUG is set to "true"
# Use queue "long" for jobs up to 120 hours
# Use queue "normal" for jobs up to 8 hours
# Use queue "low" for jobs up to 4 hours
# Use queue "ldan" for LDAN jobs
# Again multiply threads at the end by the number of reserved cores by 2 (or slightly less if you worry about memory usage)
if [[ "$DEBUG" == "true" ]]; then
    trap '(read -p "[$BASH_SOURCE:$LINENO] $BASH_COMMAND ")' DEBUG
fi

# define usage once
USAGE="qsub -v DEM=/path/to/dem.tif,IMAGES=/path/to/list/of/tifs.txt,CAMERAS=/path/to/list/of/jsons.txt,MAPPROJ_DATA=/path/to/mapproj_data.txt,OVERLAP_LIST=/path/to/overlap_list.txt,BA_PREFIX=ba0/run $0"
# Ensure a DEM was provided
if [[ -z "$DEM" || ! -e "$DEM" ]]; then
    echo "Error: DEM is not set. Use $USAGE"
    exit 1
fi
echo "DEM file: $DEM"
# Ensure a image list is provided
if [[ -z "$IMAGES" || ! -e "$IMAGES" ]]; then
    echo "Error: IMAGES is not set. Use $USAGE"
    exit 1
fi
echo "Path to images list: $IMAGES"
# Ensure a camera list is provided
if [[ -z "$CAMERAS" || ! -e "$CAMERAS" ]]; then
    echo "Error: CAMERAS is not set. Use $USAGE"
    exit 1
fi
echo "Path to cameras list: $CAMERAS"
# If we aren't refining a existing bundle adjust using terrain ignore these
if [[ -z $USE_DEM_HEIGHTS ]]; then
    # Ensure the map projected images + the DEM as the last file are included as a list
    if [[ -z "$MAPPROJ_DATA" || ! -e "$MAPPROJ_DATA" ]]; then
        echo "Error: IMAGES is not set. Use $USAGE"
        exit 1
    fi
    echo "Path to mapprojected data list: $MAPPROJ_DATA"
    # get overlap list file
    if [[ -z "$OVERLAP_LIST" || ! -e "$OVERLAP_LIST" ]]; then
        echo "Error: OVERLAP_LIST is not set. Use $USAGE"
        exit 1
    fi
    echo "Path to overlap list: $OVERLAP_LIST"
fi
# Ensure a output prefix is provided
if [[ -z "$BA_PREFIX" ]]; then
    echo "Error: BA_PREFIX is not set. Use $USAGE"
    exit 1
fi
echo "Output Prefix: $BA_PREFIX"
# If max pairwise matches isn't set, default to 1000
if [[ -z "$MAX_PAIRWISE_MATCHES" ]]; then
    export MAX_PAIRWISE_MATCHES=1000
fi
echo "Using MAX_PAIRWISE_MATCHES: $MAX_PAIRWISE_MATCHES"
# Set Robust Threshold, use "5.0" first then re-run at "2.0" with RESUME_PREFIX set to the BA prefix
if [[ -z "$ROBUST_THRESHOLD" ]]; then
    export ROBUST_THRESHOLD=1.0
fi
echo "Using ROBUST_TRESHOLD: $ROBUST_THRESHOLD"
# determine if this is a refinement pass with DEM 
if [[ -n $USE_DEM_HEIGHTS ]]; then
    export KIND='ref'
elif [[ -n $RESUME_PREFIX ]]; then
    export KIND='res'
else 
    export KIND='pt2'
fi
echo "This is a $KIND run"
# Ensure the work dir is set to something
if [[ -z "$WORKDIR" ]]; then
    # we will default to the current working directory wherever that is
    export WORKDIR="$PWD"
fi
echo "Workdir: $WORKDIR"
##############################################
# Check if the user want's this acutally submitted to PBS
if [[ -n $SUBMIT ]]; then
    # Tell user you requested to submit and then wait 15 seconds to allow user to exit just in case!
    echo "User requested to submit to PBS!!!!! You have 15 seconds to abort!!!"
    # unset SUBMIT so that this isn't recursive
    unset SUBMIT
    # unset DEBUG so that we don't debug inside the job
    unset DEBUG
    # echo SUBMIT and DEBUG as sanity check
    echo "DEBUG is $DEBUG and SUBMIT is $SUBMIT" 
    # actually sleep
    sleep 15
    # submit to qsub # Use -V to pass in all environment variables!
    submit_name="pbs_ba_${KIND}_${BA_PREFIX%/*}"
    exec qsub -N "$submit_name" -o "$WORKDIR/$submit_name.log" -V "$0"
    # be sure to exit the script at this point
    exit 0
fi
##############################################
# IF we are actually on PBS do another unset on DEBUG 
# just in case to avoid long waits for quick exits
if [[ -n $PBS_O_WORKDIR ]]; then
    # log
    echo "Checking current DEBUG variable value: $DEBUG"
    # unset it
    unset DEBUG
    # log
    echo "If DEBUG was not unset it should now be not set: $DEBUG"
fi
# Change to the working directory
echo Working directory is "$PBS_O_WORKDIR"
if [[ -n $PBS_O_WORKDIR ]]; then
    cd "$PBS_O_WORKDIR" || exit
fi
echo "machine is $(uname -a)"
echo "machine file is $PBS_NODEFILE"
# get the number of unique nodes 
if [[ -z "$PBS_NODEFILE" || ! -f "$PBS_NODEFILE" ]]; then
    NUM_NODES=1
else
    echo "machines are: $(cat $PBS_NODEFILE | sort -u)"
    NUM_NODES=$(sort -u "$PBS_NODEFILE" | wc -l)
fi
echo "running on $NUM_NODES nodes"
echo
##############################################
# source asp environment
source init_asp.sh
# echo out ISISDATA and ISISROOT
echo ISIS data is "$ISISDATA" 
echo ISIS root is "$ISISROOT"
# echo out PATH
echo PATH is "$PATH"
##############################################

# https://stereopipeline.readthedocs.io/en/latest/tools/parallel_bundle_adjust.html
# --entry-point 2 should mean only optimization occurs, which is limited to 1 node
# don't bother providing the nodelist as now we only need to use 1 node for pt 2
# https://stereopipeline.readthedocs.io/en/latest/sfs_usage.html#validation-of-bundle-adjustment
# consider higher robust threshold value and --input-adjustments-prefix with  --match-files-prefix
# then re-run with robust threshold 2
# think --input-adjustments-prefix  would be ba0/ba0 for the first round
# think --match-files-prefix would also be ba0/ba0, although if I enter only at optimization I don't think I need this as it implies skip matching
# well, actually I may want to expose it if for example I want to refine a bundle adjustment
# later I can consider --fixed-image-list so I can "lock in" images that have low residuals

# construct args
args=(
      --entry-point 2           
      --image-list "$IMAGES"    
      --camera-list "$CAMERAS"  
      --mapproj-dem "$DEM"     
      --processes 1            
      --threads 72              
      --nodata-value 0.001      
      --ip-detect-method 1      
      --ip-per-tile  400        
      --ip-per-image 20000      
      --num-iterations 500      
      --num-passes 2            
      --min-matches 50          
      --max-pairwise-matches "$MAX_PAIRWISE_MATCHES"
      --camera-weight 0           
      --robust-threshold "$ROBUST_THRESHOLD"     
      --tri-weight 0.1            
      --tri-robust-threshold 0.25 
      --min-triangulation-angle 0.1 
      --remove-outliers-params "75.0 3.0 100 100"    
      -o "$BA_PREFIX" 
)

if [[ -n "$SAVE_INTERMEDIATE_CAMERAS" ]]; then
    args+=(--save-intermediate-cameras)
fi

if [[ -n "$MAPPROJ_DATA" ]]; then
    args+=(--mapprojected-data-list "$MAPPROJ_DATA")
fi

if [[ -n "$OVERLAP_LIST" ]]; then
    args+=(--overlap-list "$OVERLAP_LIST")
fi

if [[ -n "$RESUME_PREFIX" ]]; then
    # TODO presumably if I resume a bundle adjust I'd want to continue using the 
    # same prefix as the input BA_PREFIX, or if I want more flexibility I could 
    # allow a different prefix to be used
    echo "We are resuming bundle adjust ${RESUME_PREFIX%/*}"
    args+=(--input-adjustments-prefix "$RESUME_PREFIX")
fi

if [[ -n $FIXED_IMAGES ]]; then
    # add fixed images list if defined
    echo "We are assuming certain cameras are good to go and fixing their position in ${FIXED_IMAGES}"
    args+=(--fixed-image-list "$FIXED_IMAGES")
fi

if [[ -n $USE_DEM_HEIGHTS ]]; then
    echo "We will use heights from the dem: ${DEM} as a constraint"
    args+=(--heights-from-dem "$DEM" --heights-from-dem-uncertainty 10.0 --heights-from-dem-robust-threshold 0.1)
    if [[ -z "$MATCH_FILES_PREFIX" && -z "$CLEAN_MATCH_FILES_PREFIX" ]]; then
        echo "ERROR! YOU SHOULD REALLY HAVE 'MATCH_FILES_PREFIX' or 'CLEAN_MATCH_FILES_PREFIX' SET TO PRIOR BA PASS!"
        exit 1
    fi
fi

if [[ -n $MATCH_FILES_PREFIX ]]; then
    echo "We will use match files from a previous bundle adjust ${MATCH_FILES_PREFIX}"
    args+=(--match-files-prefix "$MATCH_FILES_PREFIX")
fi
if [[ -n $CLEAN_MATCH_FILES_PREFIX ]]; then
    echo "We will use clean match files from a previous bundle adjust ${CLEAN_MATCH_FILES_PREFIX}"
    args+=(--clean-match-files-prefix "$CLEAN_MATCH_FILES_PREFIX")
fi
# create output folders as needed
LOGS_FOLDER="$WORKDIR/logs"
JOBS_FOLDER="$WORKDIR/jobs"
mkdir -p "$LOGS_FOLDER"
mkdir -p "$JOBS_FOLDER"
# set log file names
LOG_FILE="$LOGS_FOLDER/pbs_ba_${KIND}_${BA_PREFIX%/*}_$(date +"%Y-%m-%d_%H-%M-%S")_log.txt"
JOB_FILE="$JOBS_FOLDER/pbs_ba_${KIND}_${BA_PREFIX%/*}_job.log"
# start call
if [[ -z "$DEBUG" && -n $PBS_JOBID ]]; then 
    echo "Args: "
    echo "${args[@]}"
    echo "Parallel options: "
    echo "$parallel_opts"
    echo "Log File: "
    echo "$LOG_FILE"
    echo "Job File: "
    echo "$JOB_FILE"
    echo "Parallel has started at $(date)"
    parallel_bundle_adjust "${args[@]}" | grep -E -v ".ech.adjust|.match" &>> "$LOG_FILE"
    # The jobs have actually completed 
    echo "Parallel has finished with all jobs at $(date)"
    # move the joblog file to preserve its state and to avoid re-running it
    mv "$JOB_FILE" "$JOBS_FOLDER/completed_${JOB_FILE##*/}"
else
    # I am debugging of a pfe or something
    echo "would have run: "
    echo "parallel_bundle_adjust" "${args[@]}"
fi
# we are now done!
echo "Job finished at $(date)"