#!/bin/bash
#PBS -N pbs_calibrate_edr       
#PBS -j oe                      
#PBS -k oe                      
#PBS -l select=1:ncpus=20:model=ivy,walltime=08:00:00        
#PBS -q normal                  
#PBS -m abe                     
#PBS -M andrew.m.annex@nasa.gov 
#PBS -o pbs_calibrate_edr.log   
#PBS -r y                       
#PBS -S /bin/bash               
#PBS -V                         
#PBS -W group_list=e2305  

# Enable stepwise debugging if DEBUG is set to "true"
if [[ "$DEBUG" == "true" ]]; then
    trap '(read -p "[$BASH_SOURCE:$LINENO] $BASH_COMMAND ")' DEBUG
fi
# Ensure an input directory is provided
if [[ -z "$INPUT_DIR" ]]; then
    echo "Error: INPUT_DIR is not set. Use qsub -v INPUT_DIR=/path/to/IMG/files calibrate_edr.pbs"
    exit 1
fi
echo "Path to CUBs: $INPUT_DIR"
# Ensure the work dir is set to something
if [[ -z "$WORKDIR" ]]; then
    # we will default to the current working directory wherever that is
    export WORKDIR="$PWD"
fi
echo "Workdir: $WORKDIR"
##############################################
# Check if the user want's this acutally submitted to PBS
if [[ -n $SUBMIT ]]; then
    # Tell user you requested to submit and then wait 15 seconds to allow user to exit just in case!
    echo "User requested to submit to PBS!!!!! You have 15 seconds to abort!!!"
    # unset SUBMIT so that this isn't recursive
    unset SUBMIT
    # unset DEBUG so that we don't debug inside the job
    unset DEBUG
    # echo SUBMIT and DEBUG as sanity check
    echo "DEBUG is $DEBUG and SUBMIT is $SUBMIT" 
    # actually sleep
    sleep 15
    # submit to qsub
    submit_name="pbs_calibrate_edr"
    exec qsub -N "$submit_name" -o "$WORKDIR/$submit_name.log" -V "$0"
    # be sure to exit the script at this point
    exit 0
fi
##############################################
# IF we are actually on PBS do another unset on DEBUG 
# just in case to avoid long waits for quick exits
if [[ -n "$PBS_O_WORKDIR" ]]; then
    # log
    echo "Checking current DEBUG variable value: $DEBUG"
    # unset it
    unset DEBUG
    # log
    echo "If DEBUG was not unset it should now be not set: $DEBUG"
fi
# Change to the working directory
echo Working directory is "$PBS_O_WORKDIR"
if [[ -n $PBS_O_WORKDIR ]]; then
    cd "$PBS_O_WORKDIR" || exit
fi
echo "machine is $(uname -a)"
echo "machine file is $PBS_NODEFILE"
# get the number of unique nodes 
if [[ -z "$PBS_NODEFILE" || ! -f "$PBS_NODEFILE" ]]; then
    NUM_NODES=1
else
    NUM_NODES=$(sort -u "$PBS_NODEFILE" | wc -l)
fi
echo "running on $NUM_NODES nodes"
echo
##############################################
# source asp environment
source init_asp.sh
# echo out ISISDATA and ISISROOT
echo ISIS data is "$ISISDATA" 
echo ISIS root is "$ISISROOT"
# echo out PATH
echo PATH is "$PATH"
################################################
# create output folders as needed
LOGS_FOLDER="$WORKDIR/logs"
JOBS_FOLDER="$WORKDIR/jobs"
mkdir -p "$LOGS_FOLDER"
mkdir -p "$JOBS_FOLDER"
# set log file names
LOG_FILE="$LOGS_FOLDER/pbs_calibrate_edr_job_$(date +"%Y-%m-%d_%H-%M-%S")_log.txt"
JOB_FILE="$JOBS_FOLDER/pbs_calibrate_edr_job.log"
# find the IMG files and parallel the jobs
# Create a temp file
TMPFILE=$(mktemp "$WORKDIR/calibrate_edr_cmds.XXXXXX")
# Ensure cleanup on exit or error
trap 'rm -f "$TMPFILE"' EXIT
# Generate commands dynamically and store in temp file # NOTE if you need to do more complicated stuff here look at maprpoj_ba.pbs
find "$INPUT_DIR" -type f -name '*.IMG' -exec echo "calibrate_edr.sh {}" \; >> "$TMPFILE"
# log we are about to start 
# https://www.gnu.org/software/parallel/parallel.html#options
echo "launching jobs"
if [[ -z "$DEBUG" ]]; then 
    # Run GNU Parallel with the temp file if not in debug mode
    if [[ $NUM_NODES -gt 1 ]]; then
        $ASPROOT/bin/parallel -u --resume-failed --sshdelay 0.1 --joblog "$JOB_FILE" --sshloginfile "$PBS_NODEFILE" < "$TMPFILE" &> "$LOG_FILE"
    else
        $ASPROOT/bin/parallel -u --resume-failed --joblog "$JOB_FILE" < "$TMPFILE" &> "$LOG_FILE"
    fi
    # The jobs have actually completed 
    echo "Parallel has finished with all jobs at $(date)"
    # move the joblog file to preserve its state and to avoid re-running it
    mv "$JOB_FILE" "$JOBS_FOLDER/completed_${JOB_FILE##*/}"
else
    # we are in debug mode so just log out the commands that would
    # have been given the parallel
    cat "$TMPFILE"
fi
# we are now done!
echo "Job finished at $(date)"