#!/bin/bash
#PBS -N pbs_gdal_footprints
#PBS -j oe                      
#PBS -k oe                      
#PBS -l select=1:ncpus=20:model=ivy,walltime=01:00:00        
#PBS -q normal             
#PBS -m abe                     
#PBS -M andrew.m.annex@nasa.gov 
#PBS -o pbs_gdal_footprints.log   
#PBS -r y                       
#PBS -S /bin/bash               
#PBS -V                         
#PBS -W group_list=e2305        

# Enable stepwise debugging if DEBUG is set to "true"
if [[ "$DEBUG" == "true" ]]; then
    trap '(read -p "[$BASH_SOURCE:$LINENO] $BASH_COMMAND ")' DEBUG
fi
# define usage once
USAGE="qsub -v INPUT_DIR=/path/to/tif/files/ $0"

# Ensure an input directory is provided
if [ -z "$INPUT_DIR" ]; then
    echo "Error: INPUT_DIR is not set. Use $USAGE"
    exit 1
fi
echo "Path to TIFs: $INPUT_DIR"
# Ensure the work dir is set to something
if [[ -z "$WORKDIR" ]]; then
    # we will default to the current working directory wherever that is
    export WORKDIR="$PWD"
fi
echo "Workdir: $WORKDIR"
##############################################
# Check if the user want's this acutally submitted to PBS
if [[ -n $SUBMIT ]]; then
    # Tell user you requested to submit and then wait 15 seconds to allow user to exit just in case!
    echo "User requested to submit to PBS!!!!! You have 15 seconds to abort!!!"
    # unset SUBMIT so that this isn't recursive
    unset SUBMIT
    # unset DEBUG so that we don't debug inside the job
    unset DEBUG
    # echo SUBMIT and DEBUG as sanity check
    echo "DEBUG is $DEBUG and SUBMIT is $SUBMIT" 
    # actually sleep
    sleep 15
    # submit to qsub
    exec qsub -v INPUT_DIR="$INPUT_DIR" "$0"
    # be sure to exit the script at this point
    exit 0
fi
##############################################
# IF we are actually on PBS do another unset on DEBUG 
# just in case to avoid long waits for quick exits
if [[ -n $PBS_O_WORKDIR ]]; then
    # log
    echo "Checking current DEBUG variable value: $DEBUG"
    # unset it
    unset DEBUG
    # log
    echo "If DEBUG was not unset it should now be not set: $DEBUG"
fi
# Change to the working directory
echo Working directory is $PBS_O_WORKDIR
if [[ -n $PBS_O_WORKDIR ]]; then
    cd $PBS_O_WORKDIR
fi
echo "machine is $(uname -a)"
echo "machine file is $PBS_NODEFILE"
# get the number of unique nodes 
if [[ -z "$PBS_NODEFILE" || ! -f "$PBS_NODEFILE" ]]; then
    NUM_NODES=1
else
    echo "machines are: $(cat $PBS_NODEFILE)"
    NUM_NODES=$(sort -u "$PBS_NODEFILE" | wc -l)
fi
echo "running on $NUM_NODES nodes"
echo
##############################################
# source asp environment
source init_asp.sh
# echo out ISISDATA and ISISROOT
echo ISIS data is "$ISISDATA" 
echo ISIS root is "$ISISROOT"
# echo out PATH
echo PATH is "$PATH"
# save the path to gdal_footprint
GDAL_FOOTPRINT=$(which gdal_footprint)
################################################
##############################################
# find the CUB files and parallel the jobs
# Create a temp file
TMPFILE=$(mktemp $WORKDIR/gdal_footprints_cmds.XXXXXX)
# Ensure cleanup on exit or error
trap 'rm -f "$TMPFILE"' EXIT
# Generate commands dynamically and store in temp file
{
    trap '' DEBUG
    for file in "$INPUT_DIR"*.tif; do
        echo "$GDAL_FOOTPRINT -q -write_absolute_path -of GeoJSON ${file} ${file%.tif}.geojson" >> "$TMPFILE";
    done;
    if [[ "$DEBUG" == "true" ]]; then
        trap '(read -p "[$BASH_SOURCE:$LINENO] $BASH_COMMAND ")' DEBUG
    fi
}
# TODO how to resume processing of parallel if I get the time bounds wrong?
# https://www.gnu.org/software/parallel/parallel.html#options either --resume --resume-failed, likely the latter
# log we are about to start (TODO move below to new script)
echo "launching jobs at $(date)"
if [[ -z "$DEBUG" ]]; then 
    # Run GNU Parallel with the temp file if not in debug mode
    if [[ $NUM_NODES -gt 1 ]]; then
        $ASPROOT/bin/parallel --memfree 20G --resume-failed --controlmaster -u --sshdelay 0.5 --sshloginfile $PBS_NODEFILE --joblog ~/pbs_gdal_footprints_job.log  < "$TMPFILE" &> "$HOME/pbs_gdal_footprints_$(date +"%Y-%m-%d_%H-%M-%S")_log.txt"
    else
        $ASPROOT/bin/parallel -j 20 --memfree 20G --resume-failed -u --joblog ~/pbs_gdal_footprints_job.log  < "$TMPFILE" &> "$HOME/pbs_gdal_footprints_$(date +"%Y-%m-%d_%H-%M-%S")_log.txt"
    fi
    # The jobs have actually completed 
    echo "Parallel has finished with all jobs at $(date)"
    # move the joblog file to preserve its state and to avoid re-running it
    mv "$HOME/pbs_gdal_footprints_job.log" "$HOME/completed_$(date +"%Y-%m-%d_%H-%M-%S")_pbs_gdal_footprints_job.log"
else
    # we are in debug mode so just log out the commands that would
    # have been given the parallel
    cat "$TMPFILE"
fi
# we are now done!
echo "Job finished at $(date)"