#!/bin/bash
#PBS -N pbs_launch_stereo
#PBS -j oe                      
#PBS -k oe                      
#PBS -l select=4:ncpus=20:model=ivy,walltime=08:00:00        
#PBS -q normal
#PBS -m abe                     
#PBS -M andrew.m.annex@nasa.gov 
#PBS -o pbs_launch_stereo.log   
#PBS -r y                       
#PBS -S /bin/bash               
#PBS -V                         
#PBS -W group_list=e2305     
# Enable stepwise debugging if DEBUG is set to "true"
# Use queue "long" for jobs up to 120 hours
# Use queue "normal" for jobs up to 8 hours
# Use queue "low" for jobs up to 4 hours

# Enable stepwise debugging if DEBUG is set to "true"
if [[ "$DEBUG" == "true" ]]; then
    trap '(read -p "[$BASH_SOURCE:$LINENO] $BASH_COMMAND ")' DEBUG
fi
# define usage
USAGE="DEM=/path/to/dem.tif;INPUT_GPKG=/path/to/CUB/files/;PROJWIN_EXTENT='0 0 100 100'; $0"
# Ensure a DEM was provided
if [ -z "$DEM" ]; then
    echo "Error: DEM is not set. Use $USAGE"
    exit 1
fi
echo "DEM file: $DEM"
# Ensure a pair list file is provided (simply left and right map projected image file paths seperated by a space)
if [ -z "$IMAGE_PAIR_LIST" ]; then
    echo "Error: IMAGE_PAIR_LIST is not set. Use $USAGE"
    exit 1
fi
echo "Image Pair list file: $IMAGE_PAIR_LIST"

# similar list this time with the bundle adjust prefix and .adjusted_state.json postfix for the adjusted CSM models
if [ -z "$CAMERA_PAIR_LIST" ]; then
    echo "Error: CAMERA_PAIR_LIST is not set. Use $USAGE"
    exit 1
fi
echo "Camera Pair list file: $CAMERA_PAIR_LIST"
##############################################
# Check if the user want's this acutally submitted to PBS
if [[ -n $SUBMIT ]]; then
    # Tell user you requested to submit and then wait 15 seconds to allow user to exit just in case!
    echo "User requested to submit to PBS!!!!! You have 15 seconds to abort!!!"
    # unset SUBMIT so that this isn't recursive
    unset SUBMIT
    # unset DEBUG so that we don't debug inside the job
    unset DEBUG
    # echo SUBMIT and DEBUG as sanity check
    echo "DEBUG is $DEBUG and SUBMIT is $SUBMIT" 
    # actually sleep
    sleep 15
    # submit to qsub
    exec qsub -v DEM="$DEM",IMAGE_PAIR_LIST="$IMAGE_PAIR_LIST",CAMERA_PAIR_LIST="$CAMERA_PAIR_LIST" "$0"
    # be sure to exit the script at this point
    exit 0
fi
##############################################
# IF we are actually on PBS do another unset on DEBUG 
# just in case to avoid long waits for quick exits
if [[ -n $PBS_O_WORKDIR ]]; then
    # log
    echo "Checking current DEBUG variable value: $DEBUG"
    # unset it
    unset DEBUG
    # log
    echo "If DEBUG was not unset it should now be not set: $DEBUG"
fi
# Change to the working directory
echo Working directory is $PBS_O_WORKDIR
cd $PBS_O_WORKDIR
echo "machine is $(uname -a)"
echo "machine file is $PBS_NODEFILE"
# get the number of unique nodes 
if [[ -z "$PBS_NODEFILE" || ! -f "$PBS_NODEFILE" ]]; then
    NUM_NODES=1
else
    echo "machines are: $(cat $PBS_NODEFILE | sort -u)"
    NUM_NODES=$(sort -u "$PBS_NODEFILE" | wc -l)
fi
echo "running on $NUM_NODES nodes"
echo
##############################################
# source asap environment
source init_asap.sh
# echo out ISISDATA and ISISROOT
echo ISIS data is $ISISDATA 
echo ISIS root is $ISISROOT
# echo out PATH
echo PATH is $PATH
##############################################
# Create a temp file
TMPFILE=$(mktemp /home7/aannex/launch_stereo_cmds.XXXXXX)
# Ensure cleanup on exit or error
trap 'rm -f "$TMPFILE"' EXIT
# Generate commands dynamically and store in temp file
{
    trap '' DEBUG
    while read LIMG RIMG LCAM RCAM; do
        LBASE=$(basename "$LIMG")
        RBASE=$(basename "$RIMG")
        out_dir="run_stereo/${LBASE%%.*}__${RBASE%%.*}"
        # re-use match files from bundle adjust https://stereopipeline.readthedocs.io/en/latest/tools/bundle_adjust.html#match-files
        # stereo.default docs claim the normal match-files-prefix works only with non-mapprojected images.
        args=(
            "$LIMG" "$RIMG" "$LCAM" "$RCAM"
            --stereo-algorithm asp_mgm
            --nodata-value 0.001      
            --ip-detect-method 1      
            --ip-per-tile  400        
            --ip-per-image 20000 
            --nodes-list "$PBS_NODEFILE" 
            --subpixel-mode 9 
            --threads-singleprocess 8
            --threads-multiprocess 8
            --processes 2
            "$out_dir/run" "$DEM"
        )
        # for annoying reasons I can't seem to pass this in the array
        parallel_opts="\"--joblog $out_dir/pbs_stereo_${LBASE%%.*}_${RBASE%%.*}_job.log\""
        # first write out the parallel stereo command but first make the output dir so I can capture the logs per job
        echo "mkdir -p $out_dir && parallel_stereo ${args[@]}" --parallel-options "${parallel_opts} &> $out_dir/pbs_stereo_${LBASE%%.*}_${RBASE%%.*}_log.txt" >> "$TMPFILE";
        # I could have seperate queues and run point2dem all at the end over the nodes in order to have less dead air time
        echo "point2dem --threads 8 --errorimage --tr 1 $out_dir/run-PC.tif &> $out_dir/pbs_point2dem_${LBASE%%.*}_${RBASE%%.*}_log.txt" >> "$TMPFILE";
        # okay 
    done < <(paste $IMAGE_PAIR_LIST $CAMERA_PAIR_LIST)
    #
    if [[ "$DEBUG" == "true" ]]; then
        trap '(read -p "[$BASH_SOURCE:$LINENO] $BASH_COMMAND ")' DEBUG
    fi
}

# log we are about to start (TODO move below to new script)
echo "launching jobs"
if [[ -z "$DEBUG" && -n $PBS_JOBID ]]; then 
    # Run GNU Parallel with the temp file if not in debug mode
    # as we will run each stereo pair one at a time, we will only use parallel here
    # to spawn one job at a time. Later it could make sense to qsub these and have sub jobs instead
    ~/sw/tools/asp/bin/parallel --resume-failed -u -j 1 --joblog ~/pbs_stereo_job.log  < "$TMPFILE" &> "$HOME/pbs_stereo_$(date +"%Y-%m-%d_%H-%M-%S")_log.txt"
    # The jobs have actually completed 
    echo "Parallel has finished with all jobs at $(date)"
    # move the joblog file to preserve its state and to avoid re-running it
    mv "$HOME/pbs_stereo_job.log" "$HOME/completed_$(date +"%Y-%m-%d_%H-%M-%S")_pbs_stereo_job.log"
else
    # we are in debug mode so just log out the commands that would
    # have been given the parallel
    cat "$TMPFILE"
fi
# we are now done!
echo "Job finished at $(date)"