#!/bin/bash
#PBS -N pbs_launch_stereo
#PBS -j oe                      
#PBS -k oe                      
#PBS -l select=4:ncpus=20:model=ivy,walltime=08:00:00        
#PBS -q normal
#PBS -m abe                     
#PBS -M andrew.m.annex@nasa.gov 
#PBS -o pbs_launch_stereo.log   
#PBS -r y                       
#PBS -S /bin/bash               
#PBS -V                         
#PBS -W group_list=e2305     
# Enable stepwise debugging if DEBUG is set to "true"
# Use queue "long" for jobs up to 120 hours
# Use queue "normal" for jobs up to 8 hours
# Use queue "low" for jobs up to 4 hours

# Enable stepwise debugging if DEBUG is set to "true"
if [[ "$DEBUG" == "true" ]]; then
    trap '(read -p "[$BASH_SOURCE:$LINENO] $BASH_COMMAND ")' DEBUG
fi
# define usage
USAGE="DEM=/path/to/dem.tif;IMAGE_PAIR_LIST=/path/to/list.txt;CAMERA_PAIR_LIST=/path/to/list.txt $0"
# Ensure a DEM was provided
if [ -z "$DEM" ]; then
    echo "Error: DEM is not set. Use $USAGE"
    exit 1
fi
echo "DEM file: $DEM"
# Ensure a pair list file is provided (simply left and right map projected image file paths seperated by a space)
if [ -z "$IMAGE_PAIR_LIST" ]; then
    echo "Error: IMAGE_PAIR_LIST is not set. Use $USAGE"
    exit 1
fi
echo "Image Pair list file: $IMAGE_PAIR_LIST"
# similar list this time with the bundle adjust prefix and .adjusted_state.json postfix for the adjusted CSM models
if [ -z "$CAMERA_PAIR_LIST" ]; then
    echo "Error: CAMERA_PAIR_LIST is not set. Use $USAGE"
    exit 1
fi
echo "Camera Pair list file: $CAMERA_PAIR_LIST"
# get the optional semi-unique job NAME if it's not set
if [[ -z "$JOB_NAME_POSTFIX" ]]; then
    # get a job name postfix from the names file
    if [[ -z "$NAME_SOURCE" ]]; then
        NAME_SOURCE=/usr/share/dict/words
    fi
    JOB_NAME_POSTFIX=$(shuf "$NAME_SOURCE" | head -n 1 | awk '{print tolower($0)}')
    export JOB_NAME_POSTFIX
fi
echo "JOB_NAME_POSTFIX will be $JOB_NAME_POSTFIX"
# Ensure the work dir is set to something
if [[ -z "$WORKDIR" ]]; then
    # we will default to the current working directory wherever that is
    export WORKDIR="$PWD"
fi
echo "Workdir: $WORKDIR"
##############################################
# Check if the user want's this acutally submitted to PBS
if [[ -n $SUBMIT ]]; then
    # Tell user you requested to submit and then wait 15 seconds to allow user to exit just in case!
    echo "User requested to submit to PBS!!!!! You have 15 seconds to abort!!!"
    # unset SUBMIT so that this isn't recursive
    unset SUBMIT
    # unset DEBUG so that we don't debug inside the job
    unset DEBUG
    # echo SUBMIT and DEBUG as sanity check
    echo "DEBUG is $DEBUG and SUBMIT is $SUBMIT" 
    # actually sleep
    sleep 15
    # submit to qsub
    submit_name="pbs_launch_stereo_${JOB_NAME_POSTFIX}"
    exec qsub -N "$submit_name" -o "$submit_name.log" -V "$0"
    # be sure to exit the script at this point
    exit 0
fi
##############################################
# IF we are actually on PBS do another unset on DEBUG 
# just in case to avoid long waits for quick exits
if [[ -n $PBS_O_WORKDIR ]]; then
    # log
    echo "Checking current DEBUG variable value: $DEBUG"
    # unset it
    unset DEBUG
    # log
    echo "If DEBUG was not unset it should now be not set: $DEBUG"
fi
# Change to the working directory
echo Working directory is "$PBS_O_WORKDIR"
if [[ -n $PBS_O_WORKDIR ]]; then
    cd "$PBS_O_WORKDIR" || exit
fi
echo "machine is $(uname -a)"
echo "machine file is $PBS_NODEFILE"
# get the number of unique nodes 
if [[ -z "$PBS_NODEFILE" || ! -f "$PBS_NODEFILE" ]]; then
    NUM_NODES=1
else
    echo "machines are: $(cat $PBS_NODEFILE | sort -u)"
    NUM_NODES=$(sort -u "$PBS_NODEFILE" | wc -l)
fi
echo "running on $NUM_NODES nodes"
echo
##############################################
# source asp environment
source init_asp.sh
# echo out ISISDATA and ISISROOT
echo ISIS data is "$ISISDATA" 
echo ISIS root is "$ISISROOT"
# echo out PATH
echo PATH is "$PATH"
##############################################
# create output folders as needed
LOGS_FOLDER="$WORKDIR/logs"
JOBS_FOLDER="$WORKDIR/jobs"
mkdir -p "$LOGS_FOLDER"
mkdir -p "$JOBS_FOLDER"
# set log file names
LOG_FILE="$LOGS_FOLDER/pbs_stereo_$(date +"%Y-%m-%d_%H-%M-%S")_log_$JOB_NAME_POSTFIX.txt"
JOB_FILE="$JOBS_FOLDER/pbs_stereo_job_$JOB_NAME_POSTFIX.log"
# Create a temp file
TMPFILE=$(mktemp "$WORKDIR/launch_stereo_cmds.XXXXXX")
# Ensure cleanup on exit or error
trap 'rm -f "$TMPFILE"' EXIT
# Generate commands dynamically and store in temp file
{
    trap '' DEBUG
    while read -r LIMG RIMG LCAM RCAM; do
        LBASE=$(basename "$LIMG")
        RBASE=$(basename "$RIMG")
        out_dir="run_stereo/${LBASE%%.*}__${RBASE%%.*}"
        out_job_log="$out_dir/pbs_stereo_${LBASE%%.*}_${RBASE%%.*}_job.log"
        out_log_stereo="$out_dir/pbs_stereo_${LBASE%%.*}_${RBASE%%.*}_log.txt"
        out_log_p2d="$out_dir/pbs_point2dem_${LBASE%%.*}_${RBASE%%.*}_log.txt"
        # re-use match files from bundle adjust https://stereopipeline.readthedocs.io/en/latest/tools/bundle_adjust.html#match-files
        # stereo.default docs claim the normal match-files-prefix works only with non-mapprojected images.
        args=(
            "$LIMG" "$RIMG" "$LCAM" "$RCAM"
            --stereo-algorithm asp_mgm
            --ip-detect-method 1      
            --ip-per-tile  400        
            --ip-per-image 20000 
            --nodes-list "$PBS_NODEFILE" 
            --subpixel-mode 9 
            --threads-singleprocess 8
            --threads-multiprocess 4
            --processes 5
            "$out_dir/run" "$DEM"
        )
        # for annoying reasons I can't seem to pass this in the array
        parallel_opts="\"--joblog $out_job_log\""
        # first write out the parallel stereo command but first make the output dir so I can capture the logs per job
        echo "mkdir -p $out_dir && parallel_stereo" "${args[@]}" "--parallel-options ${parallel_opts} &> $out_log_stereo" >> "$TMPFILE";
        # I could have seperate queues and run point2dem all at the end over the nodes in order to have less dead air time
        echo "point2dem --threads 8 --errorimage --tr 1 $out_dir/run-PC.tif &> $out_log_p2d" >> "$TMPFILE";
        # okay 
    done < <(paste "$IMAGE_PAIR_LIST" "$CAMERA_PAIR_LIST")
    #
    if [[ "$DEBUG" == "true" ]]; then
        trap '(read -p "[$BASH_SOURCE:$LINENO] $BASH_COMMAND ")' DEBUG
    fi
}
# log we are about to start (TODO move below to new script)
echo "launching jobs"
if [[ -z "$DEBUG" && -n $PBS_JOBID ]]; then 
    # Run GNU Parallel with the temp file if not in debug mode
    # as we will run each stereo pair one at a time, we will only use parallel here
    # to spawn one job at a time. Later it could make sense to qsub these and have sub jobs instead
    parallel --resume-failed -u -j 1 --joblog "$JOB_FILE" < "$TMPFILE" &> "$LOG_FILE"
    # The jobs have actually completed 
    echo "Parallel has finished with all jobs at $(date)"
    # move the joblog file to preserve its state and to avoid re-running it
    mv "$JOB_FILE" "$JOBS_FOLDER/completed_${JOB_FILE##*/}"
else
    # we are in debug mode so just log out the commands that would
    # have been given the parallel
    cat "$TMPFILE"
fi
# we are now done!
echo "Job finished at $(date)"