#!/bin/bash
#PBS -N pbs_mapproj_noba
#PBS -j oe                      
#PBS -k oe                      
#PBS -l select=16:ncpus=20:model=ivy,walltime=08:00:00        
#PBS -q normal             
#PBS -m abe                     
#PBS -M andrew.m.annex@nasa.gov 
#PBS -o pbs_mapproj_noba.log   
#PBS -r y                       
#PBS -S /bin/bash               
#PBS -V                         
#PBS -W group_list=e2305        

# Enable stepwise debugging if DEBUG is set to "true"
if [[ "$DEBUG" == "true" ]]; then
    trap '(read -p "[$BASH_SOURCE:$LINENO] $BASH_COMMAND ")' DEBUG
fi
# define usage once
USAGE="qsub -v DEM=/path/to/dem.tif,INPUT_DIR=/path/to/CUB/files/ $0"
# Ensure a DEM was provided
if [ -z "$DEM" ]; then
    echo "Error: DEM is not set. Use $USAGE"
    exit 1
fi
echo "DEM file: $DEM"
# Ensure an input directory is provided
if [ -z "$INPUT_DIR" ]; then
    echo "Error: INPUT_DIR is not set. Use $USAGE"
    exit 1
fi
echo "Path to CUBs: $INPUT_DIR"
# get the optional semi-unique job NAME if it's not set
if [ -z "$JOB_NAME_POSTFIX" ]; then
    # get a job name postfix from the city names file
    export JOB_NAME_POSTFIX=`shuf ~/cities.csv | head -n 1`
fi
echo "JOB_NAME_POSTFIX will be $JOB_NAME_POSTFIX"
##############################################
# Check if the user want's this acutally submitted to PBS
if [[ -n $SUBMIT ]]; then
    # Tell user you requested to submit and then wait 15 seconds to allow user to exit just in case!
    echo "User requested to submit to PBS!!!!! You have 15 seconds to abort!!!"
    # unset SUBMIT so that this isn't recursive
    unset SUBMIT
    # unset DEBUG so that we don't debug inside the job
    unset DEBUG
    # echo SUBMIT and DEBUG as sanity check
    echo "DEBUG is $DEBUG and SUBMIT is $SUBMIT" 
    # actually sleep
    sleep 15
    # submit to qsub
    exec qsub -N "pbs_mapproj_noba_${JOB_NAME_POSTFIX}" -o "pbs_mapproj_noba_${JOB_NAME_POSTFIX}.log" -V "$0"
    # be sure to exit the script at this point
    exit 0
fi
##############################################
# IF we are actually on PBS do another unset on DEBUG 
# just in case to avoid long waits for quick exits
if [[ -n $PBS_O_WORKDIR ]]; then
    # log
    echo "Checking current DEBUG variable value: $DEBUG"
    # unset it
    unset DEBUG
    # log
    echo "If DEBUG was not unset it should now be not set: $DEBUG"
fi
# Change to the working directory
echo Working directory is $PBS_O_WORKDIR
if [[ -n $PBS_O_WORKDIR ]]; then
    cd $PBS_O_WORKDIR
fi
echo "machine is $(uname -a)"
echo "machine file is $PBS_NODEFILE"
# get the number of unique nodes 
if [[ -z "$PBS_NODEFILE" || ! -f "$PBS_NODEFILE" ]]; then
    NUM_NODES=1
else
    echo "machines are: $(cat $PBS_NODEFILE)"
    NUM_NODES=$(sort -u "$PBS_NODEFILE" | wc -l)
fi
echo "running on $NUM_NODES nodes"
echo
##############################################
# source asap environment
source init_asap.sh
# echo out ISISDATA and ISISROOT
echo ISIS data is $ISISDATA 
echo ISIS root is $ISISROOT
# echo out PATH
echo PATH is $PATH
# save the path to mapproject
MAPPROJ=`which mapproject`
################################################
##############################################
# find the CUB files and parallel the jobs
# Create a temp file
TMPFILE=$(mktemp ~/mapproj_noba_cmds.XXXXXX)
# Ensure cleanup on exit or error
trap 'rm -f "$TMPFILE"' EXIT
# Generate commands dynamically and store in temp file
# okay wait mapproj uses gnu parallel internally to farm out work 
# is it better for me to use gnu parallel directly or to just 
# run each command and pass in the node list and let gnu parallel handle it?
# to me it doesn't make 
{
    trap '' DEBUG
    for file in "$INPUT_DIR"*.ech.cub; do
        # --t_projwin $PROJWIN_EXTENT remove 
        # TODO: Change the output dtype to be UInt16 to save IO
        args=(
            "$MAPPROJ" "$DEM" "$file" "${file%%.cub}.json" "${file%%.cub}.map.noba.tif"
            --nodes-list "$PBS_NODEFILE" 
            --processes 10 
            --threads 4 
            --tr 1
            "&&" 
            /vast_swbuild/swbuild3/aannex/micromamba/envs/sfstools/bin/gdal_footprint 
            -q 
            -write_absolute_path 
            -of GeoJSON 
            "${file%%.cub}.map.noba.tif" 
            "${file%%.cub}.map.noba.geojson"
        )      
        echo "${args[@]}" >> "$TMPFILE";
    done;
    if [[ "$DEBUG" == "true" ]]; then
        trap '(read -p "[$BASH_SOURCE:$LINENO] $BASH_COMMAND ")' DEBUG
    fi
}
# TODO how to resume processing of parallel if I get the time bounds wrong?
# https://www.gnu.org/software/parallel/parallel.html#options either --resume --resume-failed, likely the latter
# log we are about to start (TODO move below to new script)
echo "launching jobs at $(date)"
if [[ -z "$DEBUG" ]]; then 
    # Run GNU Parallel with the temp file if not in debug mode
    if [[ $NUM_NODES -gt 1 ]]; then
        ~/sw/tools/asp/bin/parallel --resume-failed --controlmaster -u -j 4 --sshdelay 0.5 --sshloginfile $PBS_NODEFILE --joblog ~/pbs_mapproj_noba_${JOB_NAME_POSTFIX}_job.log  < "$TMPFILE" &> "$HOME/pbs_mapproj_noba_$(date +"%Y-%m-%d_%H-%M-%S")_${JOB_NAME_POSTFIX}_log.txt"
    else
        ~/sw/tools/asp/bin/parallel --resume-failed -u -j 1 --joblog ~/pbs_mapproj_noba_${JOB_NAME_POSTFIX}_job.log  < "$TMPFILE" &> "$HOME/pbs_mapproj_noba_$(date +"%Y-%m-%d_%H-%M-%S")_${JOB_NAME_POSTFIX}_log.txt"
    fi
    # The jobs have actually completed 
    echo "Parallel has finished with all jobs at $(date)"
    # move the joblog file to preserve its state and to avoid re-running it
    mv "$HOME/pbs_mapproj_noba_${JOB_NAME_POSTFIX}_job.log" "$HOME/completed_$(date +"%Y-%m-%d_%H-%M-%S")_pbs_mapproj_noba_${JOB_NAME_POSTFIX}_job.log"
else
    # we are in debug mode so just log out the commands that would
    # have been given the parallel
    cat "$TMPFILE"
fi
# we are now done!
echo "Job finished at $(date)"