#!/bin/bash
#PBS -N pbs_mapproj_ba       
#PBS -j oe                      
#PBS -k oe                      
#PBS -l select=10:ncpus=20:model=ivy,walltime=08:00:00        
#PBS -q normal                  
#PBS -m abe                     
#PBS -M andrew.m.annex@nasa.gov 
#PBS -o pbs_mapproj_ba.log   
#PBS -r y                       
#PBS -S /bin/bash               
#PBS -V                         
#PBS -W group_list=e2305        
# group list for job

# Enable stepwise debugging if DEBUG is set to "true"
if [[ "$DEBUG" == "true" ]]; then
    trap '(read -p "[$BASH_SOURCE:$LINENO] $BASH_COMMAND ")' DEBUG
fi
# define usage once
USAGE="qsub -v DEM=/path/to/dem.tif,INPUT_DIR=/path/to/CUB/files/,BA_PREFIX=ba0/ba0 $0"
# Ensure a DEM was provided
if [ -z "$DEM" ]; then
    echo "Error: DEM is not set. Use $USAGE"
    exit 1
fi
echo "DEM file: $DEM"
# Ensure an input directory is provided
if [ -z "$INPUT_DIR" ]; then
    echo "Error: INPUT_DIR is not set. Use $USAGE"
    exit 1
fi
echo "Path to CUBs: $INPUT_DIR"
# Ensure bundle adjust prefix was provided
if [ -z "$BA_PREFIX" ]; then
    echo "Error: BA_PREFIX is not set. Use $USAGE"
    exit 1
fi
echo "Bundle adjustment prefix: $BA_PREFIX, specifically creating TIFFs ending with map.${BA_PREFIX:0:3}.tif"
##############################################
# Change to the working directory
echo Working directory is $PBS_O_WORKDIR
if [[ -n $PBS_O_WORKDIR ]]; then
    cd $PBS_O_WORKDIR
fi
echo "machine is $(uname -a)"
echo "machine file is $PBS_NODEFILE"
# get the number of unique nodes 
if [[ -z "$PBS_NODEFILE" || ! -f "$PBS_NODEFILE" ]]; then
    NUM_NODES=1
else
    NUM_NODES=$(sort -u "$PBS_NODEFILE" | wc -l)
fi
echo "running on $NUM_NODES nodes"
echo
##############################################
# source asap environment
source init_asap.sh
# echo out ISISDATA and ISISROOT
echo ISIS data is $ISISDATA 
echo ISIS root is $ISISROOT
# echo out PATH
echo PATH is $PATH
# save the path to mapproject
MAPPROJ=`which mapproject`
################################################
##############################################
# find the CUB files and parallel the jobs
# Create a temp file
TMPFILE=$(mktemp /nobackup/aannex/mapproj_ba_cmds.XXXXXX)
# Ensure cleanup on exit or error
trap 'rm -f "$TMPFILE"' EXIT
# Generate commands dynamically and store in temp file
{
    trap '' DEBUG
    for file in "$INPUT_DIR"*.ech.cub; do
        # TODO if BA folder isn't in images folder give absolute path to ba prefix? or nah?
        echo "$MAPPROJ $DEM $file ${file%%.cub}.json ${file%%.cub}.map.${BA_PREFIX:0:3}.tif --tr 1 --bundle-adjust-prefix $BA_PREFIX" >> "$TMPFILE";
    done;
    if [[ "$DEBUG" == "true" ]]; then
        trap '(read -p "[$BASH_SOURCE:$LINENO] $BASH_COMMAND ")' DEBUG
    fi
}

# log we are about to start (TODO move below to new script)
echo "launching jobs"
if [[ -z "$DEBUG" ]]; then 
    # Run GNU Parallel with the temp file if not in debug mode
    if [[ $NUM_NODES -gt 1 ]]; then
        ~/sw/tools/asp/bin/parallel --jobs $NUM_NODES --eta --progress --line-buffer --joblog pbs_mapproj_ba_job.log --sshloginfile $PBS_NODEFILE  < "$TMPFILE"
    else
        ~/sw/tools/asp/bin/parallel --jobs $NUM_NODES --eta --progress --line-buffer --joblog pbs_mapproj_ba_job.log  < "$TMPFILE"
    fi
else
    # we are in debug mode so just log out the commands that would
    # have been given the parallel
    cat "$TMPFILE"
fi
# we are now done!
echo "Job finished at $(date)"