#!/bin/bash
#PBS -N pbs_mapproj_ba       
#PBS -j oe                      
#PBS -k oe                      
#PBS -l select=3:ncpus=20:model=ivy,walltime=08:00:00        
#PBS -q normal                 
#PBS -m abe                     
#PBS -M andrew.m.annex@nasa.gov 
#PBS -o pbs_mapproj_ba.log   
#PBS -r y                       
#PBS -S /bin/bash               
#PBS -V                         
#PBS -W group_list=e2305        
# group list for job

# Enable stepwise debugging if DEBUG is set to "true"
if [[ "$DEBUG" == "true" ]]; then
    trap '(read -p "[$BASH_SOURCE:$LINENO] $BASH_COMMAND ")' DEBUG
fi
# define usage once
USAGE="qsub -v DEM=/path/to/dem.tif,INPUT_DIR=/path/to/CUB/files/,BA_PREFIX=ba0/ba0 $0"
# Ensure a DEM was provided
if [ -z "$DEM" ]; then
    echo "Error: DEM is not set. Use $USAGE"
    exit 1
fi
echo "DEM file: $DEM"

# Ensure bundle adjust prefix was provided
if [ -z "$BA_PREFIX" ]; then
    echo "Error: BA_PREFIX is not set. Use $USAGE"
    exit 1
fi
echo "Bundle adjustment prefix: $BA_PREFIX, specifically creating TIFFs ending with map.${BA_PREFIX%/*}.tif"

# If CAMERA_LIST and IMAGE_LIST provided, use them instead of INPUT_DIR and passing in a BA prefix

if [[ -n "$CAMERA_LIST"  &&  -n "$IMAGE_LIST"  ]]; then
    # ensure list files exist
    if [[ ! -f $IMAGE_LIST ]]; then
        echo "IMAGE_LIST not found: $IMAGE_LIST"
        exit 1
    fi
    if [[ ! -f $CAMERA_LIST ]]; then
        echo "CAMERA_LIST not found: $CAMERA_LIST"
        exit 1
    fi
    # safety just in case
    unset INPUT_DIR
    export USE_LISTS="true"
    echo "Using $CAMERA_LIST and $IMAGE_LIST"
else
    # Ensure an input directory is provided
    if [ -z "$INPUT_DIR" ]; then
        echo "Error: INPUT_DIR is not set. Use $USAGE"
        exit 1
    fi
    # safety just in case
    unset CAMERA_LIST
    unset IMAGE_LIST
    #
    echo "Path to CUBs: $INPUT_DIR"
fi

##############################################
# Check if the user want's this acutally submitted to PBS
if [[ -n $SUBMIT ]]; then
    # Tell user you requested to submit and then wait 15 seconds to allow user to exit just in case!
    echo "User requested to submit to PBS!!!!! You have 15 seconds to abort!!!"
    # unset SUBMIT so that this isn't recursive
    unset SUBMIT
    # unset DEBUG so that we don't debug inside the job
    unset DEBUG
    # echo SUBMIT and DEBUG as sanity check
    echo "DEBUG is $DEBUG and SUBMIT is $SUBMIT" 
    # actually sleep
    sleep 15
    # submit to qsub
    exec qsub -N "pbs_mapproj_${BA_PREFIX%/*}" -o "pbs_mapproj_${BA_PREFIX%/*}.log" -V "$0"
    # be sure to exit the script at this point
    exit 0
fi
##############################################
# IF we are actually on PBS do another unset on DEBUG 
# just in case to avoid long waits for quick exits
if [[ -n $PBS_O_WORKDIR ]]; then
    # log
    echo "Checking current DEBUG variable value: $DEBUG"
    # unset it
    unset DEBUG
    # log
    echo "If DEBUG was not unset it should now be not set: $DEBUG"
fi
# Change to the working directory
# TODO set the work dir to be the parent to the IMAGES directory
echo Working directory is $PBS_O_WORKDIR
if [[ -n $PBS_O_WORKDIR ]]; then
    cd $PBS_O_WORKDIR
fi
echo "machine is $(uname -a)"
echo "machine file is $PBS_NODEFILE"
# get the number of unique nodes 
if [[ -z "$PBS_NODEFILE" || ! -f "$PBS_NODEFILE" ]]; then
    NUM_NODES=1
else
    echo "machines are: $(cat $PBS_NODEFILE)"
    NUM_NODES=$(sort -u "$PBS_NODEFILE" | wc -l)
fi
echo "running on $NUM_NODES nodes"
echo
##############################################
# source asap environment
source init_asp.sh
# echo out ISISDATA and ISISROOT
echo ISIS data is $ISISDATA 
echo ISIS root is $ISISROOT
# echo out PATH
echo PATH is $PATH
# save the path to mapproject
MAPPROJ=`which mapproject`
################################################
##############################################
# find the CUB files and parallel the jobs
# Create a temp file
TMPFILE=$(mktemp $HOME/mapproj_ba_${BA_PREFIX%/*}_cmds.XXXXXX)
# Ensure cleanup on exit or error
#trap 'rm -f "$TMPFILE"' EXIT
# Generate commands dynamically and store in temp file
{
    trap '' DEBUG
    # check if we are using input lists or no
    images=()
    cameras=()
    if [[ -n "$USE_LISTS" ]]; then
        # parse each list file and append to the array
        while read IMG CAM; do
            if [[ ! -f $IMG ]]; then
                echo "IMAGE not found!: $IMG"
                continue
            elif [[ ! -f $CAM ]]; then
                echo "CAMERA not found!: $CAM"
                continue
            else
                # TODO test to ensure the camera and image correspond!
                images+=($IMG)
                cameras+=($CAM)
            fi
        done < <(paste $IMAGE_LIST $CAMERA_LIST)
    else
        # grab the cubs from the input dir
        for file in "$INPUT_DIR"*.ech.cub; do
            images+=("$file")
            cameras+=("${file%%.cub}.json")
        done
    fi
    # now loop through the two arrays and save the jobs to run to the temp file
    for index in "${!images[@]}"; do
        IMG="${images[$index]}"
        CAM="${cameras[$index]}"
        #
        args_mapproj=(
            "$MAPPROJ" 
            "$DEM" 
            "$IMG" 
            "$CAM"
            "${IMG%%.cub}.map.${BA_PREFIX%/*}.tif"
            --processes 8 
            --threads 4 
            --tr 1
        )
        # use BA prefix if using input_dir
        if [[ -n "$INPUT_DIR" ]]; then
            args_mapproj+=(--bundle-adjust-prefix "$BA_PREFIX") 
        fi
        # add the node file if we are running on PBS
        if [[ -n "$PBS_NODEFILE" ]]; then
            # TODO do I really want this?
            args_mapproj+=(--nodes-list "$PBS_NODEFILE")
        fi
        # make the footprint arguments
        args_foot=(
            "&&" 
            /vast_swbuild/swbuild3/aannex/micromamba/envs/sfstools/bin/gdal_footprint 
            -q 
            -write_absolute_path 
            -of GeoJSON 
            "${IMG%%.cub}.map.${BA_PREFIX%/*}.tif" 
            "${IMG%%.cub}.map.${BA_PREFIX%/*}.geojson"
        )      
        echo "${args_mapproj[@]} ${args_foot[@]}" >> "$TMPFILE";
    done
    if [[ "$DEBUG" == "true" ]]; then
        trap '(read -p "[$BASH_SOURCE:$LINENO] $BASH_COMMAND ")' DEBUG
    fi
}

# log we are about to start (TODO move below to new script)
echo "launching jobs at $(date)"
if [[ -z "$DEBUG" && -n $PBS_JOBID ]]; then 
    # get output name
    export OUTPUT_LOG="$HOME/pbs_mapproj_ba_${BA_PREFIX%/*}_$(date +"%Y-%m-%d_%H-%M-%S")_log.txt"
    # Run GNU Parallel with the temp file if not in debug mode   
    if [[ $NUM_NODES -gt 1 ]]; then
        # run 1 job at a time
        # TODO I keep forgetting if -j is the number of jobs on each machine or in total across all nodes!
        ~/sw/tools/asp/bin/parallel --resume-failed --controlmaster -u -j 4 --sshdelay 0.5 --joblog ~/pbs_mapproj_ba_${BA_PREFIX%/*}_job.log < "$TMPFILE" &> "$OUTPUT_LOG"
    else
        ~/sw/tools/asp/bin/parallel --resume-failed -u -j 1 --joblog ~/pbs_mapproj_ba_${BA_PREFIX%/*}_job.log  < "$TMPFILE" &> "$OUTPUT_LOG"
    fi
    # The jobs have actually completed 
    echo "Parallel has finished with all jobs at $(date)"
    # move the joblog file to preserve its state and to avoid re-running it
    # TODO need to set the output log name as a variable to make this work
    mv "$OUTPUT_LOG" "$HOME/completed_$(date +"%Y-%m-%d_%H-%M-%S")_pbs_mapproj_ba_${BA_PREFIX%/*}_job.log"
else
    # we are in debug mode so just log out the commands that would
    # have been given the parallel
    cat "$TMPFILE"
fi
# we are now done!
echo "Job finished at $(date)"