#!/bin/bash
#PBS -N pbs_mapproj_noba
#PBS -j oe                      
#PBS -k oe                      
#PBS -l select=16:ncpus=10:model=ivy,walltime=06:00:00        
#PBS -q normal             
#PBS -m abe                     
#PBS -M andrew.m.annex@nasa.gov 
#PBS -o pbs_mapproj_noba.log   
#PBS -r y                       
#PBS -S /bin/bash               
#PBS -V                         
#PBS -W group_list=e2305        

# Enable stepwise debugging if DEBUG is set to "true"
if [[ "$DEBUG" == "true" ]]; then
    trap '(read -p "[$BASH_SOURCE:$LINENO] $BASH_COMMAND ")' DEBUG
fi
# define usage once
USAGE="qsub -v DEM=/path/to/dem.tif,INPUT_DIR=/path/to/CUB/files/ $0"
# Ensure a DEM was provided
if [ -z "$DEM" ]; then
    echo "Error: DEM is not set. Use $USAGE"
    exit 1
fi
echo "DEM file: $DEM"
# Ensure an input directory is provided
if [ -z "$INPUT_DIR" ]; then
    echo "Error: INPUT_DIR is not set. Use $USAGE"
    exit 1
fi
echo "Path to CUBs: $INPUT_DIR"
##############################################
# Change to the working directory
echo Working directory is $PBS_O_WORKDIR
if [[ -n $PBS_O_WORKDIR ]]; then
    cd $PBS_O_WORKDIR
fi
echo "machine is $(uname -a)"
echo "machine file is $PBS_NODEFILE"
# get the number of unique nodes 
if [[ -z "$PBS_NODEFILE" || ! -f "$PBS_NODEFILE" ]]; then
    NUM_NODES=1
else
    echo "Node file contents: "
    cat $PBS_NODEFILE
    NUM_NODES=$(sort -u "$PBS_NODEFILE" | wc -l)
fi
echo "running on $NUM_NODES nodes"
echo
##############################################
# source asap environment
source init_asap.sh
# echo out ISISDATA and ISISROOT
echo ISIS data is $ISISDATA 
echo ISIS root is $ISISROOT
# echo out PATH
echo PATH is $PATH
# save the path to mapproject
MAPPROJ=`which mapproject`
################################################
##############################################
# find the CUB files and parallel the jobs
# Create a temp file
TMPFILE=$(mktemp ~/mapproj_noba_cmds.XXXXXX)
# Ensure cleanup on exit or error
trap 'rm -f "$TMPFILE"' EXIT
# Generate commands dynamically and store in temp file
# okay wait mapproj uses gnu parallel internally to farm out work 
# is it better for me to use gnu parallel directly or to just 
# run each command and pass in the node list and let gnu parallel handle it?
# to me it doesn't make 
{
    trap '' DEBUG
    for file in "$INPUT_DIR"*.ech.cub; do
        # --t_projwin $PROJWIN_EXTENT remove 
        # TODO: Change the output dtype to be UInt16 to save IO
        echo "$MAPPROJ --processes 10 --parallel-options \"--sshdelay 0.5\" $DEM $file ${file%%.cub}.json ${file%%.cub}.map.noba.tif --tr 1" >> "$TMPFILE";
    done;
    if [[ "$DEBUG" == "true" ]]; then
        trap '(read -p "[$BASH_SOURCE:$LINENO] $BASH_COMMAND ")' DEBUG
    fi
}
# log we are about to start (TODO move below to new script)
echo "launching jobs at $(date)"
if [[ -z "$DEBUG" ]]; then 
    # Run GNU Parallel with the temp file if not in debug mode
    if [[ $NUM_NODES -gt 1 ]]; then
        ~/sw/tools/asp/bin/parallel --controlmaster -u -j 1 --sshdelay 0.5 --sshloginfile $PBS_NODEFILE --joblog ~/pbs_mapproj_noba_job.log  < "$TMPFILE"
    else
        ~/sw/tools/asp/bin/parallel --jobs $NUM_NODES --eta --progress --line-buffer --joblog ~/pbs_mapproj_noba_job.log  < "$TMPFILE"
    fi
else
    # we are in debug mode so just log out the commands that would
    # have been given the parallel
    cat "$TMPFILE"
fi
# we are now done!
echo "Job finished at $(date)"