#!/bin/bash
#PBS -N pbs_mapproj
#PBS -j oe                      
#PBS -k oe                      
#PBS -l select=1:ncpus=8:model=ivy,walltime=00:15:00        
#PBS -q low
#PBS -o pbs_mapproj.log
#PBS -r y                       
#PBS -S /bin/bash               
#PBS -V                         
#PBS -W group_list=e2305     
# Enable stepwise debugging if DEBUG is set to "true"
# Use queue "long" for jobs up to 120 hours
# Use queue "normal" for jobs up to 8 hours
# Use queue "low" for jobs up to 4 hours

# Enable stepwise debugging if DEBUG is set to "true"
if [[ "$DEBUG" == "true" ]]; then
    trap '(read -p "[$BASH_SOURCE:$LINENO] $BASH_COMMAND ")' DEBUG
fi
# define usage
USAGE="DEM=?,IMG=?,CAM=?,BA_PREFIX=? $0"
# Ensure a DEM was provided
if [[ -z "$DEM" ]]; then
    echo "Error: DEM is not set. Use $USAGE"
    exit 1
fi
echo "DEM file: $DEM"
# Image
if [[ -z "$IMG" ]]; then
    echo "Error: IMG is not set. Use $USAGE"
    exit 1
fi
echo "Image file: $IMG"
# precompute the base filename for the image
BASE=$(basename "$IMG")
# Camera
if [[ -z "$CAM" ]]; then
    echo "Error: CAM is not set. Use $USAGE"
    exit 1
fi
echo "Camera file: $CAM"
# Bundle Adjust prefix
if [[ -z "$BA_PREFIX" ]]; then
    BA_PREFIX='noba'
    export BA_PREFIX
fi
echo "Bundle Adjust Prefix: $BA_PREFIX"
# Ensure the work dir is set to something
if [[ -z "$WORKDIR" ]]; then
    # we will default to the current working directory wherever that is
    export WORKDIR="$PWD"
fi
echo "Workdir: $WORKDIR"
##############################################
# Check if the user want's this acutally submitted to PBS
if [[ -n $SUBMIT ]]; then
    # Tell user you requested to submit and then wait 15 seconds to allow user to exit just in case!
    echo "User requested to submit to PBS!!!!! You have 15 seconds to abort!!!"
    # unset SUBMIT so that this isn't recursive
    unset SUBMIT
    # unset DEBUG so that we don't debug inside the job
    unset DEBUG
    # echo SUBMIT and DEBUG as sanity check
    echo "DEBUG is $DEBUG and SUBMIT is $SUBMIT" 
    if [[ -z $NOSLEEP ]]; then
        # actually sleep if no sleep is not set
        sleep 15
    fi
    # submit to qsub
    submit_name="pbs_run_mapproj_${BA_PREFIX%/*}_${BASE%%.cub}"
    exec qsub -N "$submit_name" -o "$WORKDIR/$submit_name.log" -V "$0"
    # be sure to exit the script at this point
    exit 0
fi
##############################################
# IF we are actually on PBS do another unset on DEBUG 
# just in case to avoid long waits for quick exits
if [[ -n $PBS_O_WORKDIR ]]; then
    # log
    echo "Checking current DEBUG variable value: $DEBUG"
    # unset it
    unset DEBUG
    # log
    echo "If DEBUG was not unset it should now be not set: $DEBUG"
fi
# Change to the working directory
echo Working directory is "$PBS_O_WORKDIR"
if [[ -n $PBS_O_WORKDIR ]]; then
    cd "$PBS_O_WORKDIR" || exit
fi
echo "machine is $(uname -a)"
echo "machine file is $PBS_NODEFILE"
##############################################
# source asp environment
source init_asp.sh
# echo out ISISDATA and ISISROOT
echo ISIS data is "$ISISDATA" 
echo ISIS root is "$ISISROOT"
# echo out PATH
echo PATH is "$PATH"
# save the path to mapproject
MAPPROJ=$(which mapproject)
##############################################
# create output folders as needed
LOGS_FOLDER="$WORKDIR/logs"
JOBS_FOLDER="$WORKDIR/jobs"
mkdir -p "$LOGS_FOLDER"
mkdir -p "$JOBS_FOLDER"
# set log file
LOG_FILE="$LOGS_FOLDER/pbs_mapproj_${BASE%%.cub}.map.${BA_PREFIX%/*}_$(date +"%Y-%m-%d_%H-%M-%S")_log.txt"
# first set the map projection args
args_mapproj=(
            "$MAPPROJ" 
            "$DEM" 
            "$IMG" 
            "$CAM"
            "${IMG%%.cub}.map.${BA_PREFIX%/*}.tif"
            --processes 2 
            --threads 4 
            --tr 1
        )
# next set the footprint computation args 
args_foot=(
            /vast_swbuild/swbuild3/aannex/micromamba/envs/sfstools/bin/gdal_footprint 
            -q 
            -write_absolute_path 
            -of GeoJSON 
            "${IMG%%.cub}.map.${BA_PREFIX%/*}.tif" 
            "${IMG%%.cub}.map.${BA_PREFIX%/*}.geojson"
        )     
# Combine both into one string
PROCESS="${args_mapproj[@]} && ${args_foot[@]}"
# prepare to run the command or print the debug
if [[ -z "$DEBUG" && -n $PBS_JOBID ]]; then 
    echo "Starting Job for $IMG at $(date)" &> "$LOG_FILE"
    # first run mapproj
    eval "$PROCESS" &> "$LOG_FILE"
    # The jobs have actually completed 
    echo "Finished Job for $IMG at $(date)" &> "$LOG_FILE"
else
    # we are in debug mode so just log out the commands that would run
    echo "$PROCESS"
fi
# we are now done!
echo "Job finished at $(date)"