#!/bin/bash
#PBS -N pbs_img_corr
#PBS -j oe                      
#PBS -k oe                      
#PBS -l select=8:ncpus=20:model=ivy,walltime=08:00:00        
#PBS -q normal
#PBS -o pbs_img_corr.log
#PBS -r y                       
#PBS -S /bin/bash               
#PBS -V                         
#PBS -W group_list=e2305     
# Enable stepwise debugging if DEBUG is set to "true"
# Use queue "long" for jobs up to 120 hours
# Use queue "normal" for jobs up to 8 hours
# Use queue "low" for jobs up to 4 hours

# Enable stepwise debugging if DEBUG is set to "true"
if [[ "$DEBUG" == "true" ]]; then
    trap '(read -p "[$BASH_SOURCE:$LINENO] $BASH_COMMAND ")' DEBUG
fi
# define usage
USAGE="REF=?,SRC=? $0"
# Ensure a IMAGE_LIST was provided
if [[ -z "$REF" ]]; then
    echo "Error: $REF is not set. Use $USAGE"
    exit 1
fi
echo "REF file: $REF"
# OUT_NAME
if [[ -z "$SRC" ]]; then
    echo "Error: SRC is not set. Use $USAGE"
    exit 1
fi
echo "SRC file: $SRC"
# precompute the base filename for the output image
BASE=$(basename "$SRC")
# Ensure the work dir is set to something
if [[ -z "$WORKDIR" ]]; then
    # we will default to the current working directory wherever that is
    export WORKDIR="$PWD"
fi
echo "Workdir: $WORKDIR"
##############################################
# Check if the user want's this acutally submitted to PBS
if [[ -n $SUBMIT ]]; then
    # Tell user you requested to submit and then wait 15 seconds to allow user to exit just in case!
    echo "User requested to submit to PBS!!!!! You have 15 seconds to abort!!!"
    # unset SUBMIT so that this isn't recursive
    unset SUBMIT
    # unset DEBUG so that we don't debug inside the job
    unset DEBUG
    # echo SUBMIT and DEBUG as sanity check
    echo "DEBUG is $DEBUG and SUBMIT is $SUBMIT" 
    submit_name="pbs_run_img_corr_${BASE%%.tif}"
    echo "$submit_name"
    if [[ -z $NOSLEEP ]]; then
        # actually sleep if no sleep is not set
        sleep 15
    fi
    # submit to qsub
    exec qsub -N "$submit_name" -o "$WORKDIR/$submit_name.log" -V "$0"
    # be sure to exit the script at this point
    exit 0
fi
##############################################
# IF we are actually on PBS do another unset on DEBUG 
# just in case to avoid long waits for quick exits
if [[ -n $PBS_O_WORKDIR ]]; then
    # log
    echo "Checking current DEBUG variable value: $DEBUG"
    # unset it
    unset DEBUG
    # log
    echo "If DEBUG was not unset it should now be not set: $DEBUG"
fi
# Change to the working directory
echo Working directory is "$PBS_O_WORKDIR"
if [[ -n $PBS_O_WORKDIR ]]; then
    cd "$PBS_O_WORKDIR" || exit
fi
echo "machine is $(uname -a)"
echo "machine file is $PBS_NODEFILE"
# get the number of unique nodes 
if [[ -z "$PBS_NODEFILE" || ! -f "$PBS_NODEFILE" ]]; then
    NUM_NODES=1
else
    echo "machines are: $(cat $PBS_NODEFILE | sort -u)"
    NUM_NODES=$(sort -u "$PBS_NODEFILE" | wc -l)
    # create a new nodefile for gnu parallel
    # Create a temp file
    GNU_PARALLEL_NODEFILE=$(mktemp "$WORKDIR/pbs_imgcorr_nodes.XXXXXX")
    # Ensure cleanup on exit or error
    trap 'rm -f "$GNU_PARALLEL_NODEFILE"' EXIT
    # write out the number of jobs per node 
    DEFAULT_JOBS=12
    LOCAL_JOBS=12
    LOCAL_HOST=$(hostname -s)
    # start the output file 
    # Append the local node with LOCAL_JOBS
    echo "${LOCAL_JOBS}/${LOCAL_HOST}" > "$GNU_PARALLEL_NODEFILE"
    # Write all other nodes with DEFAULT_JOBS
    sort -u "$PBS_NODEFILE" | grep -v "^$LOCAL_HOST\$" | while read NODE; do
        echo "${DEFAULT_JOBS}/${NODE}" >> "$GNU_PARALLEL_NODEFILE"
    done
fi
echo "running on $NUM_NODES nodes"
echo
##############################################
# source asp environment
source init_asp.sh
# echo out ISISDATA and ISISROOT
echo ISIS data is "$ISISDATA" 
echo ISIS root is "$ISISROOT"
# echo out PATH
echo PATH is "$PATH"
# save the path to dem_mosaic
PAR_STEREO=$(which parallel_stereo)
##############################################
# create output folders as needed
LOGS_FOLDER="$WORKDIR/logs"
JOBS_FOLDER="$WORKDIR/jobs"
mkdir -p "$LOGS_FOLDER"
mkdir -p "$JOBS_FOLDER"
# set log file
LOG_FILE="$LOGS_FOLDER/pbs_img_corr_${BASE%%.tif}_$(date +"%Y-%m-%d_%H-%M-%S")_log.txt"
# set the args for DEM mosaic
args_parimgcorr=(
            "$PAR_STEREO" 
            --run-dir "$WORKDIR"
            --nodes-list "$GNU_PARALLEL_NODEFILE" 
            --threads-singleprocess 4
            --threads-multiprocess 4
            --processes 8
            --correlator-mode
            --ip-detect-method 1
            --ip-per-image 40000
            --num-matches-from-disparity 40000 
            --stereo-algorithm asp_mgm 
            --subpixel-mode 9 
            --max-disp-spread 50   
            "$REF" 
            "$SRC" 
            -o "haps/run-$BASE"
        ) 
# Combine both into one string
PROCESS_IMGCORR="${args_parimgcorr[@]}"
# prepare to run the command or print the debug
if [[ -z "$DEBUG" && -n $PBS_JOBID ]]; then 
    echo "Starting Job for $BASE at $(date)" >> "$LOG_FILE" 2>&1
    # run parallel stereo for image correlation
    eval "$PROCESS_IMGCORR" >> "$LOG_FILE" 2>&1
    # The jobs have actually completed 
    echo "Finished Job for $BASE at $(date)" >> "$LOG_FILE" 2>&1
else
    # we are in debug mode so just log out the commands that would run
    echo "$PROCESS"
fi
# we are now done!
echo "Job finished at $(date)"  >> "$LOG_FILE" 2>&1