#!/bin/bash
#PBS -N pbs_sfs_blend
#PBS -j oe                      
#PBS -k oe                      
#PBS -l select=1:ncpus=20:model=rom_ait,walltime=08:00:00        
#PBS -q normal
#PBS -o pbs_sfs_blend.log
#PBS -r y                       
#PBS -S /bin/bash               
#PBS -V                         
#PBS -W group_list=e2305     
# Enable stepwise debugging if DEBUG is set to "true"
# Use queue "long" for jobs up to 120 hours
# Use queue "normal" for jobs up to 8 hours
# Use queue "low" for jobs up to 4 hours

# Enable stepwise debugging if DEBUG is set to "true"
if [[ "$DEBUG" == "true" ]]; then
    trap '(read -p "[$BASH_SOURCE:$LINENO] $BASH_COMMAND ")' DEBUG
fi
# define usage
USAGE="REF_DEM=?,SFS_DEM=?,MAX_LIT=?,OUT_BLEND=?,OUT_WEIGHT=? $0"
# Ensure a REF_DEM was provided
if [[ -z "$REF_DEM" || ! -e "$REF_DEM" ]]; then
    echo "Error: REF_DEM is not set. Use $USAGE"
    exit 1
fi
echo "REF_DEM file: $REF_DEM"
# Ensure a SFS_DEM was provided
if [[ -z "$SFS_DEM" || ! -e "$SFS_DEM" ]]; then
    echo "Error: SFS_DEM is not set. Use $USAGE"
    exit 1
fi
echo "SFS_DEM file: $SFS_DEM"
# precompute the base filename for the output image
BASE=$(basename "$SFS_DEM")
# get the full path minus the extension only
STEM="${SFS_DEM%.*}"
# Ensure a MAX_LIT was provided
if [[ -z "$MAX_LIT" || ! -e "$MAX_LIT" ]]; then
    echo "Error: MAX_LIT is not set. Use $USAGE"
    exit 1
fi
echo "MAX_LIT file: $MAX_LIT"
#  Ensure a OUT_BLEND was provided
if [[ -z "$OUT_BLEND" ]]; then
    export OUT_BLEND="${STEM}.blend.tif"
fi
echo "OUT_BLEND file: $OUT_BLEND"
#  Ensure a OUT_WEIGHT was provided
if [[ -z "$OUT_WEIGHT" ]]; then
    export OUT_WEIGHT="${STEM}.weight.tif"
fi
echo "OUT_WEIGHT file: $OUT_WEIGHT"
# Ensure the work dir is set to something
if [[ -z "$WORKDIR" ]]; then
    # we will default to the current working directory wherever that is
    export WORKDIR="$PWD"
fi
echo "Workdir: $WORKDIR"
##############################################
# Check if the user want's this acutally submitted to PBS
if [[ -n $SUBMIT ]]; then
    # Tell user you requested to submit and then wait 15 seconds to allow user to exit just in case!
    echo "User requested to submit to PBS!!!!! You have 15 seconds to abort!!!"
    # unset SUBMIT so that this isn't recursive
    unset SUBMIT
    # unset DEBUG so that we don't debug inside the job
    unset DEBUG
    # echo SUBMIT and DEBUG as sanity check
    echo "DEBUG is $DEBUG and SUBMIT is $SUBMIT" 
    submit_name="pbs_run_sfs_blend_${BASE}"
    echo "$submit_name"
    if [[ -z $NOSLEEP ]]; then
        # actually sleep if no sleep is not set
        sleep 15
    fi
    # submit to qsub
    exec qsub -N "$submit_name" -o "$WORKDIR/$submit_name.log" -V "$0"
    # be sure to exit the script at this point
    exit 0
fi
##############################################
# IF we are actually on PBS do another unset on DEBUG 
# just in case to avoid long waits for quick exits
if [[ -n $PBS_O_WORKDIR ]]; then
    # log
    echo "Checking current DEBUG variable value: $DEBUG"
    # unset it
    unset DEBUG
    # log
    echo "If DEBUG was not unset it should now be not set: $DEBUG"
fi
# Change to the working directory
echo Working directory is "$PBS_O_WORKDIR"
if [[ -n $PBS_O_WORKDIR ]]; then
    cd "$PBS_O_WORKDIR" || exit
fi
echo "machine is $(uname -a)"
echo "machine file is $PBS_NODEFILE"
##############################################
# source asp environment
source init_asp.sh
# source the sfs_utils
source "$HOME/projects/sfstools/base_scripts/sfs_utilities.sh"
# echo out ISISDATA and ISISROOT
echo ISIS data is "$ISISDATA" 
echo ISIS root is "$ISISROOT"
# echo out PATH
echo PATH is "$PATH"
# save the path to dem_mosaic
SFS_BLEND=$(which sfs_blend)
GDAL_TRANSLATE=$(which gdal_translate)
##############################################
# ensure the SFS_DEM and MAX_LIT match the REF_DEM grid
VRT_SFS_DEM=$(match_vrt_extent "$REF_DEM" "$SFS_DEM")
VRT_MAX_LIT=$(match_vrt_extent "$REF_DEM" "$MAX_LIT")
##############################################
# create output folders as needed
LOGS_FOLDER="$WORKDIR/logs"
JOBS_FOLDER="$WORKDIR/jobs"
mkdir -p "$LOGS_FOLDER"
mkdir -p "$JOBS_FOLDER"
# set log file
LOG_FILE="$LOGS_FOLDER/pbs_sfs_blend_${BASE}_$(date +"%Y-%m-%d_%H-%M-%S")_log.txt"
# set the args for DEM mosaic
args_sfs_blend=(
            "$SFS_BLEND" 
            --threads 38
            --lola-dem "$REF_DEM"
            --sfs-dem "$VRT_SFS_DEM"
            --max-lit-image-mosaic "$VRT_MAX_LIT"
            --image-threshold 0.005 
            --lit-blend-length 25 
            --shadow-blend-length 5    
            --min-blend-size 50 
            --weight-blur-sigma 5 
            --cache-size-mb 4096               
            --output-dem "$OUT_BLEND"
            --output-weight "$OUT_WEIGHT"
        ) 
PROCESS_BLEND="${args_sfs_blend[@]}"
# set the args for converting the blend to a cog
out_blend_cog="${OUT_BLEND%.tif}.cog.tif"
args_blend_cog=(
   "$GDAL_TRANSLATE"
   --config GDAL_NUM_THREADS 38
   -co NUM_THREADS=38 
   -co COMPRESS=LERC_ZSTD
   -co MAX_Z_ERROR="0.1" 
   -co PREDICTOR=3 
   -ot Float32 
   -of COG 
   "$OUT_BLEND" 
   "$out_blend_cog" 
)
PROCESS_BLEND_COG="${args_blend_cog[@]}"
# set the args for converting the weight to a cog
out_weight_cog="${OUT_WEIGHT%.tif}.cog.tif"
args_weight_cog=(
   "$GDAL_TRANSLATE"
   --config GDAL_NUM_THREADS 38
   -co NUM_THREADS=38 
   -co COMPRESS=LERC_ZSTD
   -co MAX_Z_ERROR="0.01" 
   -co PREDICTOR=3 
   -ot Float32 
   -of COG 
   "$OUT_WEIGHT" 
   "$out_weight_cog" 
)
PROCESS_WEIGHT_COG="${args_weight_cog[@]}"
# prepare to run the command or print the debug
if [[ -z "$DEBUG" && -n $PBS_JOBID ]]; then 
    echo "Starting Job for $BASE at $(date)" >> "$LOG_FILE" 2>&1
    # run sfs_blend
    eval "$PROCESS_BLEND" >> "$LOG_FILE" 2>&1
    # run gdal_translate to make the blended dem a cog
    eval "$PROCESS_BLEND_COG" >> "$LOG_FILE" 2>&1
    # run gdal_translate to make the weight raster a cog
    eval "$PROCESS_WEIGHT_COG" >> "$LOG_FILE" 2>&1
    # The jobs have actually completed 
    echo "Finished Job for $BASE at $(date)" >> "$LOG_FILE" 2>&1
else
    # we are in debug mode so just log out the commands that would run
    echo "$PROCESS"
fi
# we are now done!
echo "Job finished at $(date)" >> "$LOG_FILE" 2>&1