#!/bin/bash
#PBS -N pbs_mapproj
#PBS -j oe                      
#PBS -k oe                      
#PBS -l select=1:ncpus=8:model=ivy,walltime=00:15:00        
#PBS -q low
#PBS -o pbs_mapproj.log
#PBS -r y                       
#PBS -S /bin/bash               
#PBS -V                         
#PBS -W group_list=e2305     
# Enable stepwise debugging if DEBUG is set to "true"
# Use queue "long" for jobs up to 120 hours
# Use queue "normal" for jobs up to 8 hours
# Use queue "low" for jobs up to 4 hours

# Enable stepwise debugging if DEBUG is set to "true"
if [[ "$DEBUG" == "true" ]]; then
    trap '(read -p "[$BASH_SOURCE:$LINENO] $BASH_COMMAND ")' DEBUG
fi
# define usage
USAGE="DEM=?,IMG=?,CAM=?,BA_PREFIX=? $0"
# Ensure a DEM was provided
if [[ -z "$DEM" ]]; then
    echo "Error: DEM is not set. Use $USAGE"
    exit 1
fi
echo "DEM file: $DEM"
# Image
if [[ -z "$IMG" ]]; then
    echo "Error: IMG is not set. Use $USAGE"
    exit 1
fi
echo "Image file: $IMG"
# Right Camera
if [[ -z "$CAM" ]]; then
    echo "Error: CAM is not set. Use $USAGE"
    exit 1
fi
echo "Camera file: $CAM"
# Bundle Adjust prefix
if [[ -z "$BA_PREFIX" ]]; then
    echo "Error: BA_PREFIX is not set. Use $USAGE"
    exit 1
fi
echo "Bundle Adjust Prefix: $BA_PREFIX"

# get the optional semi-unique job NAME if it's not set
if [[ -z "$JOB_NAME_POSTFIX" ]]; then
    # get a job name postfix from the city names file
    export JOB_NAME_POSTFIX=`shuf ~/cities.csv | head -n 1`
fi
echo "JOB_NAME_POSTFIX will be $JOB_NAME_POSTFIX"
##############################################
# Check if the user want's this acutally submitted to PBS
if [[ -n $SUBMIT ]]; then
    # Tell user you requested to submit and then wait 15 seconds to allow user to exit just in case!
    echo "User requested to submit to PBS!!!!! You have 15 seconds to abort!!!"
    # unset SUBMIT so that this isn't recursive
    unset SUBMIT
    # unset DEBUG so that we don't debug inside the job
    unset DEBUG
    # echo SUBMIT and DEBUG as sanity check
    echo "DEBUG is $DEBUG and SUBMIT is $SUBMIT" 
    if [[ -z $NOSLEEP ]]; then
        # actually sleep if no sleep is not set
        sleep 15
    fi
    # submit to qsub
    exec qsub -N "pbs_run_mapproj_${JOB_NAME_POSTFIX}" -o "pbs_run_mapproj_${JOB_NAME_POSTFIX}.log" -V "$0"
    # be sure to exit the script at this point
    exit 0
fi
##############################################
# IF we are actually on PBS do another unset on DEBUG 
# just in case to avoid long waits for quick exits
if [[ -n $PBS_O_WORKDIR ]]; then
    # log
    echo "Checking current DEBUG variable value: $DEBUG"
    # unset it
    unset DEBUG
    # log
    echo "If DEBUG was not unset it should now be not set: $DEBUG"
fi
# Change to the working directory
echo Working directory is $PBS_O_WORKDIR
cd $PBS_O_WORKDIR
echo "machine is $(uname -a)"
echo "machine file is $PBS_NODEFILE"
##############################################
# source asap environment
source init_asp.sh
# echo out ISISDATA and ISISROOT
echo ISIS data is $ISISDATA 
echo ISIS root is $ISISROOT
# echo out PATH
echo PATH is $PATH
# save the path to mapproject
MAPPROJ=`which mapproject`
##############################################
out_dir="$HOME/logs/mapproj/"
args_mapproj=(
            "$MAPPROJ" 
            "$DEM" 
            "$IMG" 
            "$CAM"
            "${IMG%%.cub}.map.${BA_PREFIX%/*}.tif"
            --processes 2 
            --threads 4 
            --tr 1
        )
args_foot=(
            "&&" 
            /vast_swbuild/swbuild3/aannex/micromamba/envs/sfstools/bin/gdal_footprint 
            -q 
            -write_absolute_path 
            -of GeoJSON 
            "${IMG%%.cub}.map.${BA_PREFIX%/*}.tif" 
            "${IMG%%.cub}.map.${BA_PREFIX%/*}.geojson"
        )     

# get the log path
OUTPUT_LOG="$HOME/log/mapproj/log_mapproj_${IMG%%.cub}.map.${BA_PREFIX%/*}_$(date +"%Y-%m-%d_%H-%M-%S")_log.txt"
# first write out the parallel mapproj command but first make the output dir so I can capture the logs per job
PROCESS="${args_mapproj[@]} ${args_foot[@]}&> $OUTPUT_LOG"
if [[ -z "$DEBUG" && -n $PBS_JOBID ]]; then 
    # Run GNU Parallel with the temp file if not in debug mode
    # as we will run each mapproj pair one at a time, we will only use parallel here
    # to spawn one job at a time. Later it could make sense to qsub these and have sub jobs instead
    echo "Starting Job for $IMG at $(date)" &> "$OUTPUT_LOG"
    # first run mapproj
    eval $PROCESS &> "$OUTPUT_LOG"
    # The jobs have actually completed 
    echo "Finished Job for $IMG at $(date)" &> "$OUTPUT_LOG"
else
    # we are in debug mode so just log out the commands that would run
    echo "$PROCESS"
fi
# we are now done!
echo "Job finished at $(date)"