#!/bin/bash
#PBS -N pbs_launch_stereo
#PBS -j oe                      
#PBS -k oe                      
#PBS -l select=1:ncpus=20:model=ivy,walltime=01:10:00        
#PBS -q low
#PBS -o pbs_launch_stereo.log   
#PBS -r y                       
#PBS -S /bin/bash               
#PBS -V                         
#PBS -W group_list=e2305     
# Enable stepwise debugging if DEBUG is set to "true"
# Use queue "long" for jobs up to 120 hours
# Use queue "normal" for jobs up to 8 hours
# Use queue "low" for jobs up to 4 hours

# Enable stepwise debugging if DEBUG is set to "true"
if [[ "$DEBUG" == "true" ]]; then
    trap '(read -p "[$BASH_SOURCE:$LINENO] $BASH_COMMAND ")' DEBUG
fi
# define usage
USAGE="DEM=/path/to/dem.tif;IMAGE_PAIR_LIST=/path/to/list.txt;CAMERA_PAIR_LIST=/path/to/list.txt $0"
# Ensure a DEM was provided
if [[ -z "$DEM" ]]; then
    echo "Error: DEM is not set. Use $USAGE"
    exit 1
fi
echo "DEM file: $DEM"
# Left Image
if [[ -z "$LIMG" ]]; then
    echo "Error: LIMG is not set. Use $USAGE"
    exit 1
fi
echo "Left Image file: $LIMG"
# Right Image
if [[ -z "$RIMG" ]]; then
    echo "Error: RIMG is not set. Use $USAGE"
    exit 1
fi
echo "Right Image file: $RIMG"
# Left Camera
if [[ -z "$LCAM" ]]; then
    echo "Error: LCAM is not set. Use $USAGE"
    exit 1
fi
echo "Left Image file: $LCAM"
# Right Camera
if [[ -z "$RCAM" ]]; then
    echo "Error: RCAM is not set. Use $USAGE"
    exit 1
fi
echo "Right Image file: $RCAM"
# Bundle Adjust prefix
if [[ -z "$BA_PREFIX" ]]; then
    echo "Error: BA_PREFIX is not set. Use $USAGE"
    exit 1
fi
echo "Bundle Adjust Prefix: $BA_PREFIX"
# get the optional semi-unique job NAME if it's not set
if [[ -z "$JOB_NAME_POSTFIX" ]]; then
    # get a job name postfix from the names file
    if [[ -z "$NAME_SOURCE" ]]; then
        NAME_SOURCE=/usr/share/dict/words
    fi
    JOB_NAME_POSTFIX=$(shuf "$NAME_SOURCE" | head -n 1 | awk '{print tolower($0)}')
    export JOB_NAME_POSTFIX
fi
echo "JOB_NAME_POSTFIX will be $JOB_NAME_POSTFIX"
# Ensure the work dir is set to something
if [[ -z "$WORKDIR" ]]; then
    # we will default to the current working directory wherever that is
    export WORKDIR="$PWD"
fi
echo "Workdir: $WORKDIR"
##############################################
# Check if the user want's this acutally submitted to PBS
if [[ -n $SUBMIT ]]; then
    # Tell user you requested to submit and then wait 15 seconds to allow user to exit just in case!
    echo "User requested to submit to PBS!!!!! You have 15 seconds to abort!!!"
    # unset SUBMIT so that this isn't recursive
    unset SUBMIT
    # unset DEBUG so that we don't debug inside the job
    unset DEBUG
    # echo SUBMIT and DEBUG as sanity check
    echo "DEBUG is $DEBUG and SUBMIT is $SUBMIT" 
    if [[ -z $NOSLEEP ]]; then
        # actually sleep if no sleep is not set
        sleep 15
    fi
    # submit to qsub
    submit_name="pbs_run_stereo_${JOB_NAME_POSTFIX}"
    exec qsub -N "$submit_name" -o "$submit_name.log" -V "$0"
    # be sure to exit the script at this point
    exit 0
fi
##############################################
# IF we are actually on PBS do another unset on DEBUG 
# just in case to avoid long waits for quick exits
if [[ -n $PBS_O_WORKDIR ]]; then
    # log
    echo "Checking current DEBUG variable value: $DEBUG"
    # unset it
    unset DEBUG
    # log
    echo "If DEBUG was not unset it should now be not set: $DEBUG"
fi
# Change to the working directory
echo Working directory is "$PBS_O_WORKDIR"
if [[ -n $PBS_O_WORKDIR ]]; then
    cd "$PBS_O_WORKDIR" || exit
fi
echo "machine is $(uname -a)"
echo "machine file is $PBS_NODEFILE"
# get the number of unique nodes 
if [[ -z "$PBS_NODEFILE" || ! -f "$PBS_NODEFILE" ]]; then
    NUM_NODES=1
else
    echo "machines are: $(cat $PBS_NODEFILE | sort -u)"
    NUM_NODES=$(sort -u "$PBS_NODEFILE" | wc -l)
fi
echo "running on $NUM_NODES nodes"
echo
##############################################
# source asap environment
source init_asp.sh
# echo out ISISDATA and ISISROOT
echo ISIS data is "$ISISDATA" 
echo ISIS root is "$ISISROOT"
# echo out PATH
echo PATH is "$PATH"
##############################################
# create output folders as needed
LOGS_FOLDER="$WORKDIR/logs"
JOBS_FOLDER="$WORKDIR/jobs"
mkdir -p "$LOGS_FOLDER"
mkdir -p "$JOBS_FOLDER"
# Process parameters
LBASE=$(basename "$LIMG")
RBASE=$(basename "$RIMG")
out_dir="run_stereo_${BA_PREFIX%/*}/${LBASE%%.*}__${RBASE%%.*}__${JOB_NAME_POSTFIX}"
# set log file names
STEREO_LOG_FILE="$out_dir/pbs_stereo_${LBASE%%.*}_${RBASE%%.*}_log.txt"
DEM_LOG_FILE="$out_dir/pbs_point2dem_${LBASE%%.*}_${RBASE%%.*}_log.txt"
GDAL_LOG_FILE="$out_dir/pbs_gdal_translate_${LBASE%%.*}_${RBASE%%.*}_log.txt"
OUTPUT_LOG="$LOGS_FOLDER/pbs_stereo_$(date +"%Y-%m-%d_%H-%M-%S")_log_$JOB_NAME_POSTFIX.txt"
# re-use match files from bundle adjust https://stereopipeline.readthedocs.io/en/latest/tools/bundle_adjust.html#match-files
# stereo.default docs claim the normal match-files-prefix works only with non-mapprojected images.
args=(
    "$LIMG" 
    "$RIMG" 
    "$LCAM" 
    "$RCAM"
    --stereo-algorithm asp_mgm
    --nodata-value 0.003 
    --ip-detect-method 1      
    --ip-per-tile  400        
    --ip-per-image 20000 
    --nodes-list "$PBS_NODEFILE" 
    --subpixel-mode 9 
    --threads-singleprocess 4
    --threads-multiprocess 4
    --processes 5
    "$out_dir/run" "$DEM"
)
# first write out the parallel stereo command but first make the output dir so I can capture the logs per job
STEREO_RUN="mkdir -p $out_dir && parallel_stereo ${args[@]} &> $STEREO_LOG_FILE"
# next run Point2dem
POST_PROCESS_POINTDEM="point2dem --threads 8 --errorimage --tr 1 $out_dir/run-PC.tif &> $DEM_LOG_FILE"
# next run gdal_translate
POST_PROCESS_GDAL="gdal_translate -r average -outsize 50% 50% $out_dir/run-DEM.tif $out_dir/run-DEM.half.tif &> $GDAL_LOG_FILE"
# prepare to run jobs
if [[ -z "$DEBUG" && -n $PBS_JOBID ]]; then 
    # Run GNU Parallel with the temp file if not in debug mode
    # as we will run each stereo pair one at a time, we will only use parallel here
    # to spawn one job at a time. Later it could make sense to qsub these and have sub jobs instead
    echo "Parallel starting Job at $(date)" >> "$OUTPUT_LOG" 2>&1
    # first run stereo
    eval "$STEREO_RUN" >> "$OUTPUT_LOG" 2>&1
    # next post process point2dem
    eval "$POST_PROCESS_POINTDEM" >> "$OUTPUT_LOG" 2>&1
    # next post process gdal_translate
    eval "$POST_PROCESS_GDAL" >> "$OUTPUT_LOG" 2>&1
    # The jobs have actually completed 
    echo "Parallel has finished Job at $(date)"  >> "$OUTPUT_LOG" 2>&1
else
    # we are in debug mode so just log out the commands that would
    # have been given the parallel
    echo "$STEREO_RUN"
    echo "$POST_PROCESS"
fi
# we are now done!
echo "Job finished at $(date)"  >> "$OUTPUT_LOG" 2>&1