#!/bin/bash
#PBS -N pbs_sfs
#PBS -j oe                      
#PBS -k oe                      
#PBS -l select=22:ncpus=24:model=has,walltime=24:00:00        
#PBS -q long
#PBS -m abe                     
#PBS -M annex@seti.org
#PBS -o pbs_sfs.log   
#PBS -r y                       
#PBS -S /bin/bash               
#PBS -V                         
#PBS -W group_list=e2305     
# TODO run this on the AMD nodes?
# Enable stepwise debugging if DEBUG is set to "true"
# Use queue "long" for jobs up to 120 hours
# Use queue "normal" for jobs up to 8 hours
# Use queue "low" for jobs up to 4 hours
if [[ "$DEBUG" == "true" ]]; then
    trap '(read -p "[$BASH_SOURCE:$LINENO] $BASH_COMMAND ")' DEBUG
fi

# define usage once
USAGE="qsub -V $0"
# Ensure a DEM was provided
if [ -z "$DEM" ]; then
    echo "Error: DEM is not set. Use $USAGE"
    exit 1
fi
echo "DEM file: $DEM"
# Ensure a image list is provided
if [ -z "$IMAGES" ]; then
    echo "Error: IMAGES is not set. Use $USAGE"
    exit 1
fi
echo "Path to images list: $IMAGES"
# Ensure a camera list is provided
if [ -z "$CAMERAS" ]; then
    echo "Error: CAMERAS is not set. Use $USAGE"
    exit 1
fi
echo "Path to cameras list: $CAMERAS"
# Ensure a output prefix is provided
if [ -z "$SFS_PREFIX" ]; then
    echo "Error: SFS_PREFIX is not set. Use $USAGE"
    exit 1
fi
echo "Output Prefix: $SFS_PREFIX"
# Ensure the work dir is set to something
if [[ -z "$WORKDIR" ]]; then
    # we will default to the current working directory wherever that is
    export WORKDIR="$PWD"
fi
echo "Workdir: $WORKDIR"
##############################################
# Check if the user want's this acutally submitted to PBS
if [[ -n $SUBMIT ]]; then
    # Tell user you requested to submit and then wait 15 seconds to allow user to exit just in case!
    echo "User requested to submit to PBS!!!!! You have 15 seconds to abort!!!"
    # unset SUBMIT so that this isn't recursive
    unset SUBMIT
    # unset DEBUG so that we don't debug inside the job
    unset DEBUG
    # echo SUBMIT and DEBUG as sanity check
    echo "DEBUG is $DEBUG and SUBMIT is $SUBMIT" 
    # submit to qsub # Use -V to pass in all environment variables!
    submit_name="pbs_launch_stereo_${SFS_PREFIX//\//}"
    echo "submitting  $submit_name"
    # actually sleep
    sleep 15
    exec qsub -N "$submit_name" -o "$WORKDIR/$submit_name.log" -V "$0"
    # be sure to exit the script at this point
    exit 0
fi
##############################################
# IF we are actually on PBS do another unset on DEBUG 
# just in case to avoid long waits for quick exits
if [[ -n $PBS_O_WORKDIR ]]; then
    # log
    echo "Checking current DEBUG variable value: $DEBUG"
    # unset it
    unset DEBUG
    # log
    echo "If DEBUG was not unset it should now be not set: $DEBUG"
fi
# Change to the working directory
echo Working directory is "$PBS_O_WORKDIR"
if [[ -n $PBS_O_WORKDIR ]]; then
    cd "$PBS_O_WORKDIR" || exit
fi
echo "machine is $(uname -a)"
echo "machine file is $PBS_NODEFILE"
# get the number of unique nodes 
if [[ -z "$PBS_NODEFILE" || ! -f "$PBS_NODEFILE" ]]; then
    NUM_NODES=1
else
    echo "machines are: $(cat $PBS_NODEFILE | sort -u)"
    NUM_NODES=$(sort -u "$PBS_NODEFILE" | wc -l)
    # create a new nodefile for gnu parallel
    # Create a temp file
    GNU_PARALLEL_NODEFILE=$(mktemp "$WORKDIR/pbs_sfs_nodes.XXXXXX")
    # Ensure cleanup on exit or error
    #trap 'rm -f "$GNU_PARALLEL_NODEFILE"' EXIT
    # write out the number of jobs per node 
    DEFAULT_JOBS=12
    LOCAL_JOBS=8
    LOCAL_HOST=$(hostname -s)
    # start the output file 
    # Append the local node with LOCAL_JOBS
    echo "${LOCAL_JOBS}/${LOCAL_HOST}" > "$GNU_PARALLEL_NODEFILE"
    # Write all other nodes with DEFAULT_JOBS
    sort -u "$PBS_NODEFILE" | grep -v "^$LOCAL_HOST\$" | while read NODE; do
        echo "${DEFAULT_JOBS}/${NODE}" >> "$GNU_PARALLEL_NODEFILE"
    done
fi
echo "running on $NUM_NODES nodes"
echo
##############################################
# source asp environment
source init_asp.sh
# echo out ISISDATA and ISISROOT
echo ISIS data is "$ISISDATA" 
echo ISIS root is "$ISISROOT"
# echo out PATH
echo PATH is "$PATH"
##############################################
#https://stereopipeline.readthedocs.io/en/latest/tools/parallel_sfs.html#parallel-sfs
# https://stereopipeline.readthedocs.io/en/latest/tools/sfs.html
# todo add --custom-shadow-threshold-list
# todo enable a --compute-exposures-only run and re-use with --image-exposures-prefix (not compatible with --resume option)
# todo add crater bottom curvature https://stereopipeline.readthedocs.io/en/latest/sfs_usage.html#sfs-crater-bottoms
# construct args
# TODO run-dir was critical, defaults to homedir! Tell Oleg!
args=(
      -i "$DEM"
      --run-dir "$WORKDIR"
      --nodes-list "$GNU_PARALLEL_NODEFILE"
      --processes 10
      --threads 4
      --tile-size 256
      --padding 64
      --cache-size-mb 2048        
      --image-list "$IMAGES"    
      --camera-list "$CAMERAS"
      --shadow-threshold 0.005
      --allow-borderline-data 
      --crop-input-images
      --blending-dist 10
      --min-blend-size 48
      --smoothness-weight 0.08
      --initial-dem-constraint-weight 0.001
      --reflectance-type 1
      --max-iterations 5
      --save-sparingly
      --resume
      -o "$SFS_PREFIX"
)
# create output folders as needed
LOGS_FOLDER="$WORKDIR/logs"
JOBS_FOLDER="$WORKDIR/jobs"
mkdir -p "$LOGS_FOLDER"
mkdir -p "$JOBS_FOLDER"
# set log file names
LOG_FILE="$LOGS_FOLDER/pbs_sfs_${SFS_PREFIX//\//}_$(date +"%Y-%m-%d_%H-%M-%S")_log.txt"
JOB_FILE="$JOBS_FOLDER/pbs_sfs_${SFS_PREFIX//\//}_job.log"
# for annoying reasons I can't seem to pass this in the array
parallel_opts=(
    -u 
    --workdir "$WORKDIR"
    --memfree 20G
    --retries 10
    --resume-failed 
    --keep-order
    --joblog "$JOB_FILE"
)
if [[ $NUM_NODES -gt 1 ]]; then
    parallel_opts+=(
        --controlmaster 
        --sshdelay 0.1 
        --sshloginfile "$GNU_PARALLEL_NODEFILE"
    )
else
    parallel_opts+=(
        --jobs "$DEFAULT_JOBS"
    )
fi
if [[ -n $FLOAT_ALBEDO ]]; then
    echo "We will add the optional --float-albedo option to sfs"
    args+=(--float-albedo)
fi

if [[ -n $CROP_WIN ]]; then
    echo "We will crop the DEM to $CROP_WIN (xoff yoff width height)"
    args+=(--crop-win "$CROP_WIN")
fi
echo "Using these opts for parallel: "
echo "${parallel_opts[@]}"
if [[ -z "$DEBUG" && -n "$PBS_JOBID" ]]; then 
    $ASPROOT/bin/parallel_sfs "${args[@]}" --parallel-options '${parallel_opts[@]}' >> "$LOG_FILE" 2>&1
    #$ASPROOT/bin/parallel_sfs "${args[@]}" --parallel-options "-u --keep-order --joblog '$JOB_FILE' --workdir '$WORKDIR' --controlmaster --sshdelay 0.1" #>> "$LOG_FILE" 2>&1
    # The jobs have actually completed 
    echo "Parallel has finished with all jobs at $(date)"
    # move the joblog file to preserve its state and to avoid re-running it
    mv "$JOB_FILE" "$JOBS_FOLDER/completed_${JOB_FILE##*/}"
else
    # I am debugging of a pfe or something
    echo "would have run: "
    echo "parallel_sfs ${args[@]}"
fi
# we are now done!
echo "Job finished at $(date)"