#!/bin/bash
#PBS -N pbs_shadow_mask       
#PBS -j oe                      
#PBS -k oe                      
#PBS -l select=1:ncpus=128:model=rom_ait,walltime=8:00:00          
#PBS -q normal                  
#PBS -m abe                     
#PBS -M andrew.m.annex@nasa.gov 
#PBS -o pbs_shadow_mask.log   
#PBS -r y                       
#PBS -S /bin/bash               
#PBS -V                         
#PBS -W group_list=e2305  

# Enable stepwise debugging if DEBUG is set to "true"
if [[ "$DEBUG" == "true" ]]; then
    trap '(read -p "[$BASH_SOURCE:$LINENO] $BASH_COMMAND ")' DEBUG
fi
# Ensure the TIF Postfix is set to enable selecting the correct images
if [ -z "$TIF_POSTFIX" ]; then
    TIF_POSTFIX='map.noba.tif'
fi
echo "Using TIF_POSTFIX: $TIF_POSTFIX"
# Ensure an input directory is provided
if [ -z "$INPUT_DIR" ]; then
    echo "Error: INPUT_DIR is not set. Use qsub -v INPUT_DIR=/path/to/IMG/files shadow_mask.pbs"
    exit 1
fi
echo "Path to TIFs: $INPUT_DIR"
# Ensure the work dir is set to something
if [[ -z "$WORKDIR" ]]; then
    # we will default to the current working directory wherever that is
    export WORKDIR="$PWD"
fi
echo "Workdir: $WORKDIR"
# SHADOW_THRESHOLD default should be 0.005, use 0.003 for sun down ridge fixes
if [[ -z $SHADOW_THRESHOLD ]]; then
    SHADOW_THRESHOLD=0.003
fi
echo "SHADOW_THRESHOLD: $SHADOW_THRESHOLD"
##############################################
# Check if the user want's this acutally submitted to PBS
if [[ -n $SUBMIT ]]; then
    # Tell user you requested to submit and then wait 15 seconds to allow user to exit just in case!
    echo "User requested to submit to PBS!!!!! You have 15 seconds to abort!!!"
    # unset SUBMIT so that this isn't recursive
    unset SUBMIT
    # unset DEBUG so that we don't debug inside the job
    unset DEBUG
    # echo SUBMIT and DEBUG as sanity check
    echo "DEBUG is $DEBUG and SUBMIT is $SUBMIT" 
    # actually sleep
    sleep 15
    # submit to qsub
    exec qsub -v INPUT_DIR="$INPUT_DIR" "$0"
    # be sure to exit the script at this point
    exit 0
fi
##############################################
# IF we are actually on PBS do another unset on DEBUG 
# just in case to avoid long waits for quick exits
if [[ -n $PBS_O_WORKDIR ]]; then
    # log
    echo "Checking current DEBUG variable value: $DEBUG"
    # unset it
    unset DEBUG
    # log
    echo "If DEBUG was not unset it should now be not set: $DEBUG"
fi
# Change to the working directory
echo Working directory is "$PBS_O_WORKDIR"
if [[ -n $PBS_O_WORKDIR ]]; then
    cd "$PBS_O_WORKDIR" || exit
fi
echo "machine is $(uname -a)"
echo "machine file is $PBS_NODEFILE"
# get the number of unique nodes 
if [[ -z "$PBS_NODEFILE" || ! -f "$PBS_NODEFILE" ]]; then
    NUM_NODES=1
else
    echo "machines are: $(cat $PBS_NODEFILE | sort -u)"
    NUM_NODES=$(sort -u "$PBS_NODEFILE" | wc -l)
    # create a new nodefile for gnu parallel
    # Create a temp file
    GNU_PARALLEL_NODEFILE=$(mktemp "$WORKDIR/pbs_shadow_mask_nodes.XXXXXX")
    # Ensure cleanup on exit or error
    trap 'rm -f "$GNU_PARALLEL_NODEFILE"' EXIT
    # write out the number of jobs per node 
    DEFAULT_JOBS=256
    LOCAL_JOBS=256
    LOCAL_HOST=$(hostname -s)
    # start the output file 
    # Append the local node with LOCAL_JOBS
    echo "${LOCAL_JOBS}/${LOCAL_HOST}" > "$GNU_PARALLEL_NODEFILE"
    # Write all other nodes with DEFAULT_JOBS
    sort -u "$PBS_NODEFILE" | grep -v "^$LOCAL_HOST\$" | while read NODE; do
        echo "${DEFAULT_JOBS}/${NODE}" >> "$GNU_PARALLEL_NODEFILE"
    done
fi
echo "running on $NUM_NODES nodes"
echo
##############################################
# make sure the CWD is the INPUT_DIR
# source asap environment
source init_sfstools.sh
# echo out PATH
echo PATH is "$PATH"
cd "$INPUT_DIR" || exit
# save the path to shadowmask
SHADOW_MASK=$(which shadow_mask.sh)
echo "Path to shadow_mask.sh: $SHADOW_MASK"
##############################################
# create output folders as needed
LOGS_FOLDER="$WORKDIR/logs"
JOBS_FOLDER="$WORKDIR/jobs"
mkdir -p "$LOGS_FOLDER"
mkdir -p "$JOBS_FOLDER"
# set log file names
JOB_FILE="$JOBS_FOLDER/pbs_shadow_mask_job.log"
LOG_FILE="$LOGS_FOLDER/pbs_shadow_mask_$(date +"%Y-%m-%d_%H-%M-%S")_log.txt"
# find the IMG files and parallel the jobs
# Create a temp file
TMPFILE=$(mktemp "$WORKDIR/shadow_mask_cmds.XXXXXX")
# Ensure cleanup on exit or error
trap 'rm -f "$TMPFILE"' EXIT
# Generate commands dynamically and store in temp file # NOTE if you need to do more complicated stuff here look at maprpoj_ba.pbs
find "$INPUT_DIR" -type f -name "*.$TIF_POSTFIX" -exec echo "$SHADOW_MASK" '{}' \; >> "$TMPFILE"
# sort the TMPFILE to ensure repeatability
sort -o "$TMPFILE"{,}
#
# log we are about to start 
# https://www.gnu.org/software/parallel/parallel.html#options
echo "launching jobs"
if [[ -z "$DEBUG" ]]; then 
    # Run GNU Parallel with the temp file if not in debug mode 
    parallel_opts=(
        -u 
        -a "$TMPFILE"
        --workdir "$WORKDIR"
        --env CONDA_PREFIX
        --memfree 10G
        --retries 10
        --resume-failed 
        --keep-order
        --joblog "$JOB_FILE"
    )
    if [[ $NUM_NODES -gt 1 ]]; then
        parallel_opts+=(
            --controlmaster 
            --sshdelay 0.05
            --sshloginfile "$GNU_PARALLEL_NODEFILE"
        )
    else
        parallel_opts+=(
            --jobs "$DEFAULT_JOBS"
        )
    fi
    # echo out parallel opts
    echo "Using these opts for parallel: "
    echo "${parallel_opts[@]}"
    # DON'T USE ASP's parallel call it modified the python path!!! make sure you update PYTHONHOME WITHIN 
    # start gnu parallel
    $ASPROOT/bin/parallel "${parallel_opts[@]}" &> "$LOG_FILE"
    # The jobs have actually completed 
    echo "Parallel has finished with all jobs at $(date)"
    # move the joblog file to preserve its state and to avoid re-running it
    mv "$JOB_FILE" "$JOBS_FOLDER/completed_$(date +"%Y-%m-%d_%H-%M-%S")_${JOB_FILE##*/}"
else
    # we are in debug mode so just log out the commands that would
    # have been given the parallel
    cat "$TMPFILE"
fi
rm -f "$GNU_PARALLEL_NODEFILE"
echo "Job finished at $(date)"