#!/usr/bin/env bash
##############################################
# source bashrc
[ -f ~/.bashrc ] && source ~/.bashrc
# source asap environment
source init_sfstools.sh
micromamba activate SfsPipeline
export PYTHONHOME=$CONDA_PREFIX
################################################
# Must have 1 arguments. Print usage on failure.
if [ "$#" -ne 2 ]; then
    echo "Usage: $0 <i> <shadow threshold>"
    exit 1
fi
# must have gdal_calc/etc in path
if ! command -v gdal_calc 2>&1 >/dev/null
then
    echo "gdal_calc could not be found"
    exit 1
fi
# must have gdalinfo in path
if ! command -v gdalinfo 2>&1 >/dev/null
then
    echo "gdalinfo could not be found"
    exit 1
fi
# must have gdal_footprint in path
if ! command -v gdal_footprint 2>&1 >/dev/null
then
    echo "gdal_footprint could not be found"
    exit 1
fi

in_img=$1
SHADOW_THRESHOLD=$2
tmp_mask=${in_img%.tif}.mask.tif
out_mask_geojson=${in_img%.tif}.mask.geojson
out_json=${in_img%.tif}.mask.stats.json
# disable temp file creation for the purpose of this script, theoretically fine to leave but I want fewer random files laying around
export GDAL_PAM_ENABLED=NO
# compute the mask for shadows using gdal calc 
# TODO: I am suspicious a simple threshold like this won't be robust enough
# be a little pesimistic, if you lose terrain that is at the noise floor you couldn't match anyways
gdal_calc --quiet -A $in_img --calc="(2*(A>$SHADOW_THRESHOLD))+(A<=$SHADOW_THRESHOLD)" --outfile $tmp_mask --NoData=0 --type Byte --overwrite --co=COMPRESS=LZW --co=NBITS=2
# compute the stats for the mask 
gdalinfo $tmp_mask -hist -json | jq --arg IMG ${in_img##*/}  -c '{'img': $IMG, 'shadowed': .bands[0].histogram.buckets[1], 'illuminated': .bands[0].histogram.buckets[2], 'total_area': (.size[0] * .size[1])}' > $out_json
# recompute the mask 
gdal_calc --quiet -A $in_img --calc="A>$SHADOW_THRESHOLD" --outfile $tmp_mask --NoData=0 --type Byte --overwrite --co=COMPRESS=LZW --co=NBITS=1
# ensure the new geometry will be generated by deleting the old geojson file
if [[ -f $out_mask_geojson ]]; then
    rm $out_mask_geojson
fi
# now only the good illuminated pixels are not nodata, can't get stats per say but can get geometry
# now this program can run into issues if it runs into a topology issue, so let's do a gracefull re-attempt if that occurs
try_run() {
    local tmp_err=$(mktemp)
    "$@" 2> "$tmp_err"
    local rc=$?
    if [[ -s "$tmp_err" || $rc -ne 0 ]]; then
        echo "Attempt failed: $*" >&2
        cat "$tmp_err" >&2
        rm "$tmp_err"
        rm "$out_mask_geojson"
        return 1
    fi
    rm "$tmp_err"
    return 0
}

#gdal_footprint -q -overwrite -write_absolute_path -max_points 5000 -simplify 10 $tmp_mask -of GeoJSON $out_mask_geojson
if try_run gdal_footprint -q -overwrite -write_absolute_path -max_points 5000 -simplify 10 $tmp_mask -of GeoJSON $out_mask_geojson; then
    echo "Success making a footprint for $tmp_mask using variant 1"
elif try_run gdal_footprint -q -overwrite -write_absolute_path -max_points 4000 $tmp_mask -of GeoJSON $out_mask_geojson; then
    echo "Success making a footprint for $tmp_mask using variant 2"
elif try_run gdal_footprint -q -overwrite -write_absolute_path -max_points 3000 $tmp_mask -of GeoJSON $out_mask_geojson; then
    echo "Success making a footprint for $tmp_mask using variant 3"
elif try_run gdal_footprint -q -overwrite -write_absolute_path -max_points 2500 $tmp_mask -of GeoJSON $out_mask_geojson; then
    echo "Success making a footprint for $tmp_mask using variant 4"
elif try_run gdal_footprint -q -overwrite -write_absolute_path -max_points 2000 $tmp_mask -of GeoJSON $out_mask_geojson; then
    echo "Success making a footprint for $tmp_mask using variant 5"
elif try_run gdal_footprint -q -overwrite -write_absolute_path -max_points 1000 $tmp_mask -of GeoJSON $out_mask_geojson; then
    echo "Success making a footprint for $tmp_mask using variant 6"
elif try_run gdal_footprint -q -overwrite -write_absolute_path -max_points 500 $tmp_mask -of GeoJSON $out_mask_geojson; then
    echo "Success making a footprint for $tmp_mask using variant 7"
elif try_run gdal_footprint -q -overwrite -write_absolute_path $tmp_mask -of GeoJSON $out_mask_geojson; then
    echo "Success making a footprint for $tmp_mask using variant 8"
else
    echo "All attempts at computing the footprint for $tmp_mask failed" >&2
    exit 1
fi

# now we are done 
echo "Finished $in_img"
exit 0